- prow/config/external_plugins_config.yaml
No response when we use `/merge` command on  tidb-community-bots/ti-community-bot
> config: add merge config for tidb-community-bots/ti-community-bot

- prow/cluster/ti_community_autoresponder_deployment.yaml
- prow/cluster/ti_community_blunderbuss_deployment.yaml
- prow/cluster/ti_community_label_deployment.yaml
- prow/cluster/ti_community_lgtm_deployment.yaml
- prow/cluster/ti_community_merge_deployment.yaml
- prow/cluster/ti_community_owners_deployment.yaml
- prow/cluster/ti_community_tars_deployment.yaml
- prow/config/external_plugins_config.yaml
Add exclude labels for tiup.
Because you cannot manually add `status/can-merge`.（Only ti-community-merge can add it.）
> build: bump ti-community-prow plugins and config tiup

- cmd/merge/main.go
Drop path as this is trivially determined from the call signature. It is also already included in the returned error on L97.
https://github.com/tidb-community-bots/configs/blob/c83fcb3527d6c0ec44fc3f5497620d74c2b5722d/cmd/merge/main.go#L97
> fix: log the error

- .prow.yaml
- prow/cluster/branchprotector.yaml
- prow/cluster/crier_deployment.yaml
- prow/cluster/deck_deployment.yaml
- prow/cluster/ghproxy.yaml
- prow/cluster/hook_deployment.yaml
- prow/cluster/horologium_deployment.yaml
- prow/cluster/needs-rebase_deployment.yaml
- prow/cluster/plank_deployment.yaml
- prow/cluster/prow_controller_manager_deployment.yaml
- prow/cluster/sinker_deployment.yaml
- prow/cluster/statusreconciler_deployment.yaml
- prow/cluster/ti_community_autoresponder_deployment.yaml
- prow/cluster/ti_community_blunderbuss_deployment.yaml
- prow/cluster/ti_community_label_deployment.yaml
- prow/cluster/ti_community_lgtm_deployment.yaml
- prow/cluster/ti_community_merge_deployment.yaml
- prow/cluster/ti_community_owners_deployment.yaml
- prow/cluster/ti_community_tars_deployment.yaml
- prow/cluster/tide_deployment.yaml
- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
Bump version prow version from v20201204-d90be1ef6b to v2020117-2de500de27
And bump plugins version from v0.16.1 to v0.16.5
part of https://github.com/ti-community-infra/configs/issues/63
> build: bump prow version

- prow/config/external_plugins_config.yaml
The `release-1.1` branch only require one LGTM.
> config: add branches configuration item for tidb-operator

- prow/cluster/ti_community_autoresponder_deployment.yaml
- prow/cluster/ti_community_blunderbuss_deployment.yaml
- prow/cluster/ti_community_label_deployment.yaml
- prow/cluster/ti_community_lgtm_deployment.yaml
- prow/cluster/ti_community_merge_deployment.yaml
- prow/cluster/ti_community_owners_deployment.yaml
- prow/cluster/ti_community_tars_deployment.yaml
Part of https://github.com/ti-community-infra/configs/issues/63
> build: bump plugins version from v0.16.5 to v0.16.6

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Now that PR supports multiple sigs, we need to redesign the plugin.
> config: disable blunderbuss for tikv

- prow/config/config.yaml
reprotest 1.16 added in https://github.com/pingcap/tiup/pull/1130
reprotest 1.13 removed in https://github.com/pingcap/tiup/pull/1151
So update the CI config.
> feat: tiup: update reprotest task

- prow/config/config.yaml
Without this option, the bot as administrator will force a PR merge after the PR has out-of-date.
> fix: enable enforce_admins for tikv/tidb-operator

- prow/config/config.yaml
For pingcap org, the CLA is signed, so we can just set the body to empty.
For tikv org, the DOC will be signed, so to ensure that each DCO is recorded effectively, use the GitHub default squash body.
> config: uniform commit message format for tikv and pingcap

- prow/config/config.yaml
Close https://github.com/ti-community-infra/tichi/issues/393
As some of PR in TiUP repo may not run all of the CI jobs, just remove required mark for them and let bot wait to all checks to pass before commit merge.
> feat: tiup: not marking required checks but wait for all to success

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
close #151 
- pingcap/docs
- pingcap/docs-cn
- pingcap/docs-tidb-operator
- pingcap/docs-dm
- ti-community-lgtm
- ti-community-merge
- ti-community-owners (By default, PR must have at least one lgtm)
- ti-community-label
- welcome
- assign
- hold
- wip
- size (Use the size plugin to automatically add size label to PR, replaces the original size label manually added)
- require-matching-label (All PRs need to add translation/* label)
> config: enable tichi for docs / docs-cn / docs-dm / docs-tidb-operator

- prow/config/config.yaml
Actually we don't need to query the docs repository separately.
> config: freeze release-4.0 for tidb/tikv and cleanup the docs repositories query

- prow/config/config.yaml
Cancel freeze release-4.0 for pingcap/tidb and tikv/tikv. The cherry-pick-approved label is no longer required for the release-4.0 branch.
> config: cancel freeze release-4.0 for tidb/tikv

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Add lifecycle plugin for the repository: pingcap/docs、pingcap/docs-cn、pingcap/docs-dm、pingcap/docs-tidb-operator.
At the same time, in order to avoid conflicts, cancel the response of the ti-community-label plugin to the `/lifecycle` command prefix.
You can view related commands through [Command Help](https://prow.tidb.io/command-help#close).
> config: enable lifecycle and require-matching-label ignore PR with -cherry-pick label for docs repo

- prow/config/config.yaml
For the release branch, we want to strictly restrict push permissions.
> config: add restrictions to tikv and tidb release branchs

- prow/config/external_plugins_config.yaml
Some tests need to be triggered explicitly by command and will not be triggered automatically when there is a new commit.
> config: Modify pingcap/ticdc tars message to support triggering all tests

- prow/config/labels.yaml
I don't think this repository uses these labels.
> config: remove some useless labels

- prow/config/plugins.yaml
The retitle plugin allows users to re-title pull requests and issues where GitHub permissions don't allow them to.
> config: enable retitle for docs sig repos

- prow/cluster/needs-rebase_deployment.yaml
It seems that the upgrade has encountered some problems, so it is temporarily downgraded.
```
{"component":"needs-rebase","error":"pull request head changed while checking mergeability (f12bd4c6294ebf0084f1a13487275fa10c0e2df8 -\u003e 5037bbed8d763c6adcdd1224cd0ca39e90c5666a)","event-GUID":"4ebc10d8-9791-11eb-913e-bdbb0dc11f83","event-type":"issue_comment","file":"prow/external-plugins/needs-rebase/main.go:184","func":"main.(*Server).handleEvent.func2","head-sha":"f12bd4c6294ebf0084f1a13487275fa10c0e2df8","level":"info","msg":"Error handling event.","org":"pingcap","plugin":"needs-rebase","pr":23365,"repo":"tidb","severity":"info","time":"2021-04-07T11:06:40Z"}
```
> build: downgrade needs-rebase version

- prow/cluster/ti_community_tars_deployment.yaml
Because tidb's tests are unstable and accumulate a large number of PRs that can be merged, the regular update time is adjusted to reduce the pressure of CI's tests.
> config: set tars update period to 2h

- prow/config/plugins.yaml
Sending pull request event doesn't help tars. Because we are now only handling can-merge pr.
If there is a new commit then can-merge is cancelled, and if it is a bot commit then there is no need to send it. I'll remove that part of the code tonight.
> config: stop send pull request event to tars

- prow/jobs/pingcap/tidb/tidb-bot-periodics.yaml
Since the update period of tars is adjusted to 20m, it needs to be adjusted.
> config: adjust the updated time to 25m for tidb retester

- prow/config/external_plugins_config.yaml
Under this config, tichi will auto-cc qiancai in docs-tidb-operator.
> config: add qiancai for auto-cc of docs-tidb-operator

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
I found that tidb-dashboard was not using tichi to merge PRs, and after checking, I found that tichi could not automatically merge PRs because the repository did not enable the tars plugin to help merge bases. so this PR will enable tars for tidb-dashboard.
> config: enable tars for tidb dashboard

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Explicitly adding this label to the PRs of release branch can help us reduce the tars merge base.
> config: enable cherry-pick-unapproved for tidb

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
release-5.0-rc is no longer maintained.
Now tide only queries the master and 4.0 and 5.0 of these repositories.
> config: clean up 5.0-rc configurations

- prow/config/external_plugins_config.yaml
This PR appends a lot of inactive reviewers of Chaos Mesh for avoiding `/auto-cc` assigning;
The list of inactive reviewers contains "oraluben", so I think we could close https://github.com/ti-community-infra/configs/pull/295
> chore: appending inactive reviewers

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
We did a migration for labels and forgot to change these regex.
> fix: Do not remind for missing labels on the release branch

- prow/config/labels.yaml
This PR adds labels for the following two repos:
chaos-mesh/website
chaos-mesh/website-zh
> config: Add labels for chaos-mesh/website

- prow/config/config.yaml
Make the tide required for SIG-docs repositories.
> config: Make the tide required for SIG-docs repositories

- prow/config/external_plugins_config.yaml
Signed-off-by: HunDunDM <hundundm@gmail.com>
In `ti-community-blunderbuss`, the config of `tikv/pd` uses `include_reviewers` instead of `exclude_reviewers`.
related #311
> config: update the list of auto-assigned reviewers for pd

- prow/config/external_plugins_config.yaml
In ti-community-blunderbuss, the config of pingcap/dm uses include_reviewers instead of exclude_reviewers.
part of #311
> config: update the list of auto-assigned reviewers for pingcap/dm

- prow/config/external_plugins_config.yaml
In ti-community-blunderbuss, the config of pingcap/dumpling uses include_reviewers instead of exclude_reviewers.
part of #311
> config: update the list of auto-assigned reviewers for pingcap/dumpling

- prow/config/external_plugins_config.yaml
In `ti-community-blunderbuss`, the config of `tikv/ticdc` uses `include_reviewers` instead of `exclude_reviewers`.
ref #311
> config: update the list of auto-assigned reviewers for ticdc

- prow/config/external_plugins_config.yaml
In `ti-community-blunderbuss`, the config of `pingcap/tidb-tools` uses `include_reviewers` instead of `exclude_reviewers`.
ref #311
> config: update the list of auto-assigned reviewers for tidb-tools

- prow/config/config.yaml
- prow/config/plugins.yaml
Because go-releaser collects PR titles for us as changelog, it is useless to enable the plugin. (It was just for testing.)
> config: disable release-note for tichi

- prow/config/external_plugins_config.yaml
In ti-community-blunderbuss, the config of pingcap/br uses include_reviewers instead of exclude_reviewers.
ref #311
> config: update the list of auto-assigned reviewers for BR

- prow/config/external_plugins_config.yaml
In `ti-community-blunderbuss`, the config of `pingcap/tidb-operator` uses `include_reviewers` instead of `exclude_reviewers`.
related #311
> config: update the list of auto-assigned reviewers for tidb-operator

- prow/config/plugins.yaml
Signed-off-by: tison <wander4096@gmail.com>
@Mini256 @hi-rustin I'm unsure the pipeline of cherry-pick. We should remove `/lgtm` term but can we have another suggestive description?
> config: remove lgtm term in cherry_pick_unapproved

- prow/cluster/ti_community_tars_deployment.yaml
ref: https://github.com/ti-community-infra/tichi/pull/563
```log
{"client":"github","file":"/home/runner/go/pkg/mod/k8s.io/test-infra@v0.0.0-20210529014624-ff1bf8b1a1bc/prow/github/client.go:761","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"UpdatePullRequestBranch(pingcap, dm)","time":"2021-06-03T06:19:41Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8dac3d]
goroutine 74 [running]:
k8s.io/test-infra/prow/github.(*client).UpdatePullRequestBranch(0xc00070fb30, 0xc0007de827, 0x7, 0xc0007de798, 0x2, 0x6a3, 0x0, 0x0, 0x0)
/home/runner/go/pkg/mod/k8s.io/test-infra@v0.0.0-20210529014624-ff1bf8b1a1bc/prow/github/client.go:4046 +0x39d …
```
> fix: revert tars from v1.5.13 to v1.5.12

- prow/config/config.yaml
```log
{"component":"branchprotector","error":"update ti-community-infra: update ti-community-bot: update master from protected=false: get policy: ti-community-infra/ti-community-bot=master defines a policy, which requires protect: true","file":"prow/cmd/branchprotector/protect.go:159","func":"main.main","level":"error","msg":"0","severity":"error","time":"2021-06-15T09:31:29Z"}
{"component":"branchprotector","file":"prow/cmd/branchprotector/protect.go:161","func":"main.main","level":"fatal","msg":"Encountered 1 errors protecting branches","severity":"fatal","time":"2021-06-15T09:31:29Z"}
```
> fix: refine ti-community-bot branch protection

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.yaml
We will create a new branch release-5.1 for the following two doc repos on June 22 so this PR is to add the related bot configurations. 
pingcap/docs-cn
pingcap/docs
> config: add the bot configuration for v5.1 branch in two doc repos

- prow/config/config.yaml
* tikv: remove required contexts on integration tests. 
* All integration test will be triggered after pr  merged
> config(tikv): remove required contexts on integration tests

- prow/config/config.yaml
* pd: remove required contexts on integration tests.
* All integration test will be triggered after pr merged
> config(pd): remove required contexts on integration tests

- prow/config/config.yaml
decoupling tikv build binary logic from ci integration-common-test.
* remove required context integration-common-test
* add context build
> config(tikv): remove context integration-common-test,add context build

- prow/config/external_plugins_config.yaml
ticdc almost cherrypick all PR, in order to reduce the cost of our review, we would like to be able to copy the relevant labels of the code merge control, through the cherry-pick-approved label control merge.
> config(ticdc): copy all the labels for ticdc

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
This reverts commit c2c11ec7a6915e6fb79647bb673bf3adaaf6841d.
Remove timely autorespond after july 1st and written before.
> config: Revert "config: auto respond to lgtm (#334)"

- prow/config/labels.md
- prow/config/labels.yaml
This PR adds the `type/compatibility-or-feature-change` label and modifies the description of `type/bug-fix` for docs-cn and docs repositories.
> config: add one type label in two doc repos

- prow/cluster/ti_community_autoresponder_deployment.yaml
- prow/cluster/ti_community_blunderbuss_deployment.yaml
- prow/cluster/ti_community_cherrypicker_deployment.yaml
- prow/cluster/ti_community_contribution_deployment.yaml
- prow/cluster/ti_community_label_blocker_deployment.yaml
- prow/cluster/ti_community_label_deployment.yaml
- prow/cluster/ti_community_lgtm_deployment.yaml
- prow/cluster/ti_community_merge_deployment.yaml
- prow/cluster/ti_community_owners_deployment.yaml
- prow/cluster/ti_community_tars_deployment.yaml
- prow/cluster/tichi_web_deployment.yaml
- prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
CherryPicker will no longer request the reviewers of the original PR.
> build(bump): bump all ti plugins version from v1.6.0 to v1.7.0

- prow/config/config.yaml
Ref: https://github.com/pingcap/ticdc/pull/2409, `Lint` check has been removed.
Other checks are kept the same required_status_checks with release-5.0/release-5.1 and master branch in release-4.0.
> config(ticdc): remove some required_status_checks in release-4.0

- prow/config/external_plugins_config.yaml
Because when using `/merge` command the bot will record the current commit to keep track of whether there are new commits, and then cancel merge.
Since cherry-pick's PR does not record the commit, the label disappears automatically when the bot merges base.
So it is currently not possible to copy the can-merge label directly.
cc: @amyangfei
> config(ticdc): ignore the can-merge and ptal labels

- prow/config/external_plugins_config.yaml
Allow @nongfushanquan add  cherry-pick-approved label on PR of `pingcap/dumpling` / `pingcap/dm` / `pingcap/ticdc` / `pingcap/br` repos.
> config: add cherry-pick-approved trusted users

- prow/config/external_plugins_config.yaml
Fix the problem of inconsistency between tars and tide, which will cause tars to perform redundant merge master operations and fail to complete the merge, this wastes a lot of CI resources.
> config: add exclude labels for tars

- prow/config/config.yaml
dumpling has updated the integration tests requirements in https://github.com/pingcap/dumpling/pull/325
> config(dumpling): update dumpling integration test requirements

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
- The `cherry-pick-unapproved` plugin will add the `do-not-merge/cherry-pick-not-approved` label to the PR submitted to the release branch. 
- The robot will not perform merge base operations and merge pull request operations on PRs with the label of `do-not-merge/cherry-pick-not-approved`
- Only release team members can add the `cherry-pick-approved` label and cancel the `do-not-merge/cherry-pick-not-approved` label.
> feat: enable cherry-pick-unapproved for tics

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
Enable release-5.2 config for the following repo:
- pingcap/tidb
- pingcap/dumpling
- pingcap/tidb-tools
- pingcap/tidb-binlog
- pingcap/parser
- tikv/pd
- tikv/tikv
The following repo has not yet checkout the release-5.2 branch:
- pingcap/docs
- pingcap/docs-cn
- pingcap/br
> feat: add release-5.2 config for some repo

- prow/cluster/ti_community_autoresponder_deployment.yaml
- prow/cluster/ti_community_blunderbuss_deployment.yaml
- prow/cluster/ti_community_cherrypicker_deployment.yaml
- prow/cluster/ti_community_contribution_deployment.yaml
- prow/cluster/ti_community_label_blocker_deployment.yaml
- prow/cluster/ti_community_label_deployment.yaml
- prow/cluster/ti_community_lgtm_deployment.yaml
- prow/cluster/ti_community_merge_deployment.yaml
- prow/cluster/ti_community_owners_deployment.yaml
- prow/cluster/ti_community_tars_deployment.yaml
- prow/cluster/tichi_web_deployment.yaml
- prow/config/external_plugins_config.yaml
- prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
part of   https://github.com/pingcap/community/issues/520
add teams configs on:
- https://github.com/ti-community-infra/configs/pull/414
owners config on test-dev:
- https://github.com/ti-community-infra/tichi/blob/e1a22dde11f41b5062801cf05388f225761e26fe/configs/prow-dev/config/external_plugins_config.yaml#L16
test on: 
- https://github.com/ti-community-infra/test-dev/pull/423 (use_gtihub_permission)
- https://github.com/ti-community-infra/test-dev/pull/422 (auth base on sig)
owners link:
- https://prow-dev.tidb.io/tichi/repos/ti-community-infra/test-dev/pulls/423/owners
- https://prow-dev.tidb.io/tichi/repos/ti-community-infra/test-dev/pulls/422/owners
> build: bump ti plugins to v1.8.0

- prow/cluster/ti_community_autoresponder_deployment.yaml
- prow/cluster/ti_community_blunderbuss_deployment.yaml
- prow/cluster/ti_community_cherrypicker_deployment.yaml
- prow/cluster/ti_community_contribution_deployment.yaml
- prow/cluster/ti_community_label_blocker_deployment.yaml
- prow/cluster/ti_community_label_deployment.yaml
- prow/cluster/ti_community_lgtm_deployment.yaml
- prow/cluster/ti_community_merge_deployment.yaml
- prow/cluster/ti_community_owners_deployment.yaml
- prow/cluster/ti_community_tars_deployment.yaml
- prow/cluster/tichi_web_deployment.yaml
- prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
This reverts commit df1ffa7dc8829812296c90203fee38933b4e7a2f.
> config: Revert "build: bump ti plugins version from v1.8.1 to v1.8.2 (#423)"

- prow/config/config.yaml
https://internals.tidb.io/t/topic/374/15?u=mini256
https://github.com/pingcap/tidb/pull/28249
**Notice**: When this PR is merged, the robot will automatically synchronize the configuration to the branch protection configuration of the GitHub repository.
We enable the CODEOWNERS to implement our config review mechanism by turning on the `require_code_owner_reviews` option.
But GitHub will require us to enable the `required_approving_review_count` option at the same time, and the minimum value of this option is 1. 
It will require our PR to pass through at least one reviewer with **write permission** before it can be merged. However, our *team reviewer* only has read permission in the repository settings. 
Notice: **After enabling this option, if the PR does not get the approval of at least …
> config(tidb): enable require code owner reviews

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
It will cause some people to become review requested hotspots, so we prefer to use random assignment. I will submit an issue to track this requirement. So for now we will do manual randomization.
> config: stop autocc for ticdc

- prow/config/config.yaml
Signed-off-by: qiancai <qqzczy@126.com>
The cirlcleci/circleci: lint is no longer used, so I replace it with the new CI check condition "jenkins-docs-cn/verify" in this PR.
> config(docs-cn,docs): Replace cirlcleci/circleci: lint with jenkins-docs-cn/verify for required_status_checks

- prow/config/config.yaml
Since we have merged DM repo into TiCDC repo https://github.com/pingcap/ticdc/pull/3122, we need to add `idc-jenkins-ci-ticdc/dm-integration-test` and `idc-jenkins-ci-ticdc/dm-compatibility-test` as a required status in TiCDC CI.
> config: update required status for TiCDC

- prow/config/config.yaml
We use the GitHub code owner review feature to implement the config review mechanism.
This PR will enable the [Require review from Code Owners](https://docs.github.com/en/github-ae@latest/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule) option for TIKV, PD.
We only use the code owner review mechanism on the master branch, and the release branch is managed by cherry-pick approved.
> config(tikv,pd): enable required code owner review

- prow/config/external_plugins_config.yaml
As title.
Because the previously configured regular expression is relatively loose, the PR number in the commit message will be incorrectly matched. When the format checker finds that it is not an issue number, it thinks it violates the matching rule.
Therefore, referring to the previous voting content in TiKV community, we restrict the regular expression of format rule.
Ref Vote: https://github.com/tikv/community/pull/150
> config: limit grammar of the associate issue number

- prow/config/config.yaml
releated to https://github.com/pingcap/tics/pull/3321
* tics has a new ci tics_ghpr_unit_test, so add required status unit-test
> config(tics): add required status unit-test

- prow/config/config.yaml
as the title
[release-note-checker](https://github.com/pingcap/community/blob/master/contributors/release-note-checker.md) is deprecated in most repositories. Keeping this for br/tidb-binlog may confuse our contributors.
> config: remove check_release_note protect

- prow/config/external_plugins_config.yaml
As discussed in https://github.com/ti-community-infra/tichi/issues/743#issuecomment-993450110, we hope tichi can ignore invalid review prompt for docs repos.
> config(docs): ignore invalid review prompt for docs repos

- prow/config/external_plugins_config.yaml
Now we provided a `copy_issue_numbers_from_squashed_commit` option to make @ti-chi-bot be able to copy the issue number in the squashed commit message to cherry-pick commit when PR is in conflict.
For example, the squashed commit in the master branch has an issue number.
When PR is in conflict, the bot can't apply the patch that contains the commit history. 
When it generates cherry-pick commit, it will copy issue number from squashed commit to cherry-pick commit.
Refer: https://book.prow.tidb.io/#/plugins/cherrypicker
> config(pd): enable cherrypicker `copy_issue_numbers_from_squashed_commit` option

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Enable the following plugins for pingcap/ng-monitoring repo:
- ti-community-lgtm
- ti-community-merge
- [ti-community-cherrypicker](https://book.prow.tidb.io/#/plugins/cherrypicker)
- welcome
- wip
- assign
- hold
> config: enable tichi for ng-monitoring repo

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>
This PR updates the following:
- Update `chaos-mesh/chaos-mesh => required_status_checks => contexts`, we have recently updated the relevant checks in https://github.com/chaos-mesh/chaos-mesh/pull/2696. (This will influence the branch `master` and `release-2.1`)
- Update `chaos-mesh/website => enforce_admins` to `false`. Usually, our docs publishing is a very sampled process, so I thought the `admin` could just push to the master branch.
- Add `test` context to `chaos-mesh/website => required_status_checks`. This ensures that every change is built properly.
- Update `chaos-mesh/chaos-mesh => additional_labels`.
- Add `iguoyr` into `reviewers`.
- Add `^versioned_docs/` regexp to indicate that the document under it needs to be tracked by the …
> chore: update chaos-mesh config

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Chinese: https://book.prow.tidb.io/#/plugins/issue-triage
English: https://book.prow.tidb.io/#/en/plugins/issue-triage
Issue: https://github.com/ti-community-infra/test-prod/issues/38
PR: https://github.com/ti-community-infra/test-prod/pull/37
> config: enable issue triage check for tidb, tiflow

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Signed-off-by: Schrodinger ZHU Yifan <i@zhuyi.fan>
TiFlash is in the progress of renaming the repos. This PR moves integration scripts to a separate `tiflash-scripts` repo,  allowing main source repo to claim the name of `tiflash`.
The change is triggered by:
```
sed -i "s/pingcap\/tiflash/pingcap\/tiflash-scripts/g" $(find . -type f)
```
> config: rename pingcap/tiflash to pingcap/tiflash-scripts

- prow/config/config.yaml
Signed-off-by: JmPotato <ghzpotato@gmail.com>
https://github.com/ti-community-infra/configs/pull/524 tries to use the `report-coverage` as the final test result check to block a PR merging. But it turns out a skipped action status will also be treated as passed according to https://github.com/tikv/pd/pull/4638.
This PR makes all test chunks as required in `master` branch.
> config: update the PD required-contexts

- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
- prow/config/plugins.yaml
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>
Since there are currently two different tags about the docs, this PR unifies the label of documentation to `documentation`.
> chore: unify to documentation in chaos-mesh

- prow/config/external_plugins_config.yaml
remove @lonng and @nongfushanquan from the cherry-pick-arppoved label trusted users list.
> config: only allow release team to approve cherry-pick

- prow/config/config.yaml
Hi! We have migrated the e2e test from Jenkins to GitHub Action(https://github.com/chaos-mesh/chaos-mesh/pull/2986), the name of the check has been changed. This PR would update the configuration of the bot.
> change checks for chaos-mesh on master branch

- prow/config/config.yaml
This PR would update the configuration of checks from Jenkins to GitHub Action.
Like https://github.com/ti-community-infra/configs/pull/550, but for release-2.1
> chore: apply gha e2e test on release-2.1

- prow/config/config.yaml
> config: fix docs-cn jenkins ci name

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
- [enforce link issue check for tikv repos](https://github.com/ti-community-infra/configs/pull/558/commits/400b0b71b9d98b0468e7ae020790835235020840)
- [enable issue triage check for tikv and pd](https://github.com/ti-community-infra/configs/pull/558/commits/709a472bac217f9b3a17ce182e87ff41d3151750)
- [needs triage completed before merged on master](https://github.com/ti-community-infra/configs/pull/558/commits/8decf3b33b0864af1f63a4faaa98e99e1eacfb26)
> config: enable issue triage check for tikv and pd

- prow/config/config.yaml
* tikv release build take too long, tidb_ghpr_test already has debug build on linux amd64. remove tidb_ghpr_build ci pipeline.
> config: remove unnecessary tikv release build

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
Chaos Mesh just cut the new branch `release-2.2` for the next release v2.2.0, this PR would update the tichi bot configurations.
> chore: new branch release-2.2 for chaos mesh

- prow/config/config.yaml
Because semantic-pull-requests check service has down for a long time, remove it from the require status checks config.
Ref: https://github.com/zeke/semantic-pull-requests/issues/183
> config: remove the Semantic Pull Request CI

- prow/config/config.yaml
Set tide as a required item to prevent people from merging by mistake.
> config(ticdc): make tide required for tiflow

- prow/config/labels.md
- prow/config/labels.yaml
ref task-2 in https://github.com/pingcap/tiflow/issues/5352
> config(tiflow): add area/engine label to tiflow repo

- prow/config/external_plugins_config.yaml
Signed-off-by: STRRL <im@strrl.dev>
as https://github.com/chaos-mesh/chaos-mesh/pull/3317 is going to be merged, I create this PR for updating the taichi bot configuration
> chore: append xlgao-zju as chaos mesh committer

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
Chaos Mesh just cut the new branch release-2.3 for the next minor release v2.3.0 and related beta releases, this PR would update the tichi bot configurations.
> chore: new branch release-2.3 for chaos mesh

- prow/config/config.yaml
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
Like what we have done in https://github.com/ti-community-infra/configs/pull/579, we should modify the required check for new release.
> fix: modify chaos-mesh release-2.3 required status check

- prow/config/external_plugins_config.yaml
Version 6.0 has finished it's life cycle.
@wuhuizuo @heipark
> Config( triage ): Add "6.0" to "wontfix_verions" list.

- prow/cluster/crier_rbac.yaml
- prow/cluster/deck_rbac.yaml
- prow/cluster/hook_rbac.yaml
- prow/cluster/horologium_rbac.yaml
- prow/cluster/ing_ingress.yaml
- prow/cluster/prow_controller_manager_rbac.yaml
- prow/cluster/prowjob_customresourcedefinition.yaml
- prow/cluster/sinker_rbac.yaml
- prow/cluster/statusreconciler_rbac.yaml
- prow/cluster/tide_rbac.yaml
Ref:
- https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22?_ga=2.123900106.-1597814552.1659254325#v1-manifest
- https://raw.githubusercontent.com/kubernetes/test-infra/master/config/prow/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml
> build(prow/cluster): upgrade k8s manifests to k8s `v1.22`

- prow/config/config.yaml
ref task-3 in https://github.com/pingcap/tiflow/issues/6094
`jenkins-ticdc/verify` has covered all tests included in `idc-jenkins-ci/leak-test` and `idc-jenkins-ci-ticdc/unit-test`
Besides I can't find the test entrance of `idc-jenkins-ci/leak-test`, maybe there are configured in Jenkins backend.
`jenkins-ticdc/verify` is added since release-5.4, we can remove `idc-jenkins-ci/leak-test` from release-5.4
> config(tiflow): remove required status check of leak-test in part of branches

- prow/cluster/ing_ingress.yaml
add ingress to `prow.tidb.net`
What's Changed: add a k8s ingress resource `prow-net`
> chore(prow/cluster): add ingress to prow.prow.net

- prow/config/external_plugins_config.yaml
- prow/config/labels.yaml
for versions label from `needs-cherry-pick-to-{ .ver }` to `needs-cherry-pick-to-release-{ .ver }`:
- `6.1`
- `6.3`
- `5.3`
- `5.4`
How it Works:
> config(tidb): update needs cherry pick labels

- prow/config/external_plugins_config.yaml
cherry-pick bot will migrate from old cherry-pick bot to TiChiBot's cherry-pick plugin:
- `pingcap/br` is merged into `pingcap/tidb`, no need to split the configuration changes.
- creating of cherry-pick PR for `tikv/tikv` will be migrated to TiChiBot before this PR merged.
BREAKING CHANGE: need to manually rename labels from `needs-cherry-pick-x.y` to `needs-cherry-pick-release-x.y` after the PR merged.
How it Works:
> refactor(tikv): update `need_cherry_pick_label_prefix` for tikv

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
migrate cherry-pick PR creating from old bot to TiChiBot.
We will shutdown old bot:
github-bot deployed with ti-srebot, and it lacked mataince.
> feat(chaos-mesh/chaos-mesh): enable cherry-picker plugin

- prow/config/external_plugins_config.yaml
The separated configs of tidb under ti-community-format-checker may make the second one invalid.
> fix(ti-community-format-checker): merge tidb ti-community-format-checker configs.

- prow/cluster/jenkins-operator-deployment.yaml
it will cause dup reports with crier component, so disable it.
How it Works:
> fix(prow/cluster): disable report for jenkins-operator comonent

- prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
enable some postsubmit jobs for pingcap/tidb:
* merged_common_test
* merged_integration_common_test
* merged_integration_ddl_test
* merged_integration_jdbc_test
* merged_integration_mysql_test
* merged_sqllogic_test
> chore(prow/jobs/pingcap/tidb): add some postsubmit jobs

- prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
enable tow postsubmit jobs for pingcap/tidb:
* merged_integration_copr_test
* merged_tiflash_test
> chore(prow/jobs/pingcap/tidb): add two merged-tests to postsubmits

- prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
The following tasks have been tested for stability for two weeks. In the past two days, the success rate was over 95%, so enable context report for them.
* merged_e2e_test
* merged_common_test
* merged_integration_common_test
* merged_integration_ddl_test
* merged_integration_mysql_test
* merged_sqllogic_test
* merged_integration_copr_test
* merged_tiflash_test
> chore(prow/jobs/pingcap/tidb): enable context report for postsubmit jobs

- prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
The following pipelines has a success rate of less than 90% in the last three days, disable the reporting, and wait for the repair pr finished.
* merged_e2e_test
* merged_integration_copr_test
* merged_sqllogic_test
> chore(pingcap/tidb): disable status report for unstable mergedci

- prow/cluster/jenkins-operator-deployment.yaml
- prow/cluster/tide_deployment.yaml
- prow/config/external_plugins_config.yaml
Bump tide image and reduce GitHub api consuming in `jenkins-operator` component.
How it Works:
> fix(prow/cluster): bump tide images to support `replace` in template

- prow/cluster/ing_ingress.yaml
migrated to prow.tidb.net for serval months.
> chore(prow/cluster): offline domain prow.tidb.io

- prow/config/config.yaml
remove this reuqired status: license check has been migrated from github action to ksyun jenkins (idc-jenkins-ci-tidb/check_dev)
> chore(pingcap/tidb): remove tidb required check

- prow/config/config.yaml
Already migrated the GitHub action workflow into other pipelines.
Ref: https://github.com/PingCAP-QE/ci/pull/1722
> chore(pingcap/tiflash): remove tiflash required context `check-license` in branch protect rules

- prow/config/labels.md
- prow/config/labels.yaml
- prow/config/plugins.yaml
- fix links in comments send by `approve` plugin.
- delete labels that will be created automatically by prow plugins.
- delete labels presented end life versions.
> fix(prow/config): fix link urls for approve plugin

- prow/config/config.yaml
No need explicit contexts for prow jobs.
Ref: https://docs.prow.k8s.io/docs/components/core/tide/config/#context-policy-options
We only need to ensure `tide` in required contexts.
> chore(prow/config): delete prow job contexts in branch protection for tidb@master

- prow/config/plugins.yaml
Why:
For the initialization, we need manually create the config map to boot the prow instance, it's not automatic.
Currently we have migrate to GitOps powered by fluxcd tool, we should remove it to avoid conflicts with GitOps.
change plugins list on repos: 
- ti-community-infra/configs
- pingcap-qe/ci
> fix(prow/config): remove `config-updater` plugin on repos for GitOps

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
update bot config for `tiunimanager` and `tiunimanager-ui` repos to migrage review plugins.
Issue Number: ref pingcap/tiunimanager-ui#195
Ref: https://github.com/ti-community-infra/configs/issues/824
> config(prow/config): migrate to `lgtm` + `approve` plugins  for tiunimanager repos

- prow/config/plugins.yaml
The repo owner want to disable automatic reviewing of the `chatgpt` plugin, he want request it manually.
> config(prow/config): turn off PR events to `chatgpt` plugin on `pingcap-qe/test-infra` repo

- prow/config/external_plugins_config.yaml
Problem Summary: Migrate trigger comment to `/approve`, now we use lgtm + approve plugin for reviewing.
How it Works:
> config(prow/config): migrate tigger comment from `/merge` to `/approve` for tiflash repos

- prow/config/plugins.yaml
As title, currently many reviewers are inactive, we need manually request reviewers.
> config(prow/config): remove plugin blunderbuss for `pingcap/tiflash` repo

- prow/config/plugins.yaml
As title, currently many reviewers are inactive, we need manually request reviewers.
> config(prow/config): remove plugin blunderbuss for `pingcap/tiflow` repo

- prow/config/plugins.yaml
As title, currently many reviewers are inactive, we need manually request reviewers.
> config(prow/config): remove plugin blunderbuss for `pingcap/tidb` repo

- prow/config/external_plugins_config.yaml
`Tars` plugin can only set one label to be required, so we can not set `lgtm` + `approved` for it without modify the plugin.
Currently tiflash need 2 lgtm votes to make the PR `lgtm`ed, so `lgtm` label should be better.
We planed to refactor CI jobs for tiflash repo next month, we do not need tars plugin to refresh PRs when jobs are  refactored.
> config(prow/config): update the tars required PR label from `approved` to `lgtm`

- prow/config/external_plugins_config.yaml
- forbid remove or add `needs-*-more-lgtm` label by human.
- add auto response when user send `/merge` in repos which was migrated to new review plugins.
- set only when label to `lgtm` for `tars` external plugins.
How it Works:
> config(prow/config): update external plugin configs

- prow/config/config.yaml
Avoid the issue of prow: display `forbiden merge to` on "tide" context, but it wont affect the merging.
>  config(prow/config): add LTS release branches in to tide include branches

- prow/config/external_plugins_config.yaml
Update congfiguration of external plugin `ti-community-label-blocker`.
How it Works:
> config(pingcap/docs*): allow add `lgtm` label by document team on pull requests

- prow/config/external_plugins_config.yaml
Fix a GitHub id typo introduced in https://github.com/ti-community-infra/configs/pull/912
> prow/config: fix an id typo

- prow/config/config.yaml
Remove some required status on tiflow release-6.1 and release-6.5. 
Integration testing pipelines does not automatically trigger every push commit, we have set run_before_merged in prow presubmit config to ensure those pipeline passed before pr merged.
> config(tiflow): remove some required status on tiflow

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
Remove some required status on tiflow release-5.3 and release-5.4.
Integration testing pipelines does not automatically trigger every push commit, we have set run_before_merged in prow presubmit config to ensure those pipeline passed before pr merged.
> config(tiflow): remove some required check because prow trigger

- prow/config/config.yaml
https://github.com/pingcap/docs-tidb-operator/pull/2388 cannot be merged under the current config.
> config: allow merging pr to release-1.x in docs-tidb-operator

- prow/config/config.yaml
> config(prow/config): reduce tide query interval from 120s to 90s

- prow/config/plugins.yaml
The autoresponder plugin will reply comments on pull requests or issues when new comments matched.
I will use it to guide reviewer to use `/approve` command when received `/merge` comments.
Also update approve flow link for tikv ORG(not migrated)
> config(prow/config): add `ti-community-autoresponder` external plugin on `pingcap/*`

- prow/config/kustomization.yaml
- prow/config/openai/tasks.yaml
Why:
- `ee-ops` repo should not contain the config files that served for business logic, it's not for community.
> config(prow/config): migrate openai config from pingcap-qe/ee-ops repo

- prow/config/config.yaml
- if allow it, it may break other hotfix pull request on `mysql-test` job.
Ref:
- https://github.com/pingcap/tidb/pull/45088 `affected`
Fix: https://github.com/PingCAP-QE/ci/issues/2206
> config(prow/config): forbid merge pull request to release-x.y.z of `tidb-test` repo

- prow/config/config.yaml
Issue Number: ref https://github.com/PingCAP-QE/ci/issues/2129
- update branch protect rules for release branches
How it Works:
- Prepare to enable condition triggering on CI jobs for efficiency.
- Now the jobs will be triggered by prow bot, we just need to keep `tide` in required context list.
- The feature has enabled in trunk branch for serval weeks, It's stable and correct.
> config(prow/config): update branch protection config for `pingcap/tidb` release branches

- prow/config/config.yaml
Issue Number: ref https://github.com/PingCAP-QE/ci/issues/2129
update branch protect rules for release-6.1
How it Works:
* Prepare to enable condition triggering on CI jobs for efficiency.
* Now the jobs will be triggered by prow bot, we just need to keep tide in required context list.
* The feature has enabled in trunk branch for serval weeks, It's stable and correct.
* when it merged we need update the hot fix branch protection (by regex) manually
> config(prow/config): update branch protection config for pingcap/tidb release-6.5

- prow/config/plugins.yaml
The plugin is enabled for `pingcap/community` but not configuration label prefix for it, and it will cause unexpected comments, such as:
Disable the plugin for `pingcap/community` repo. it's no need.
How it Works:
> fix(pingcap/community): disable cherry pick external plugin

- prow/config/plugins.yaml
- the approvers' PR need self approval.
- only approving by comment "/approve" by approvers.
> chore(pingcap/tiup): update approve plugin config

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Problem Summary: blocking merging when pull request has none test tasks checked.
- add pull request format check rule on description for `pingcap/tidb`.
- add label `do-not-merge/needs-finished-tests` for `pingcap/tidb`.
- blocking merging when pull quest owned the `do-not-merge/needs-finished-tests` label
How it Works:
Check pull request description with format check external plugin.
> feat(pingcap/tidb): block mergeing for pull requests which have none finished test tasks

- prow/config/external_plugins_config.yaml
support lable ok-to-test on test-prod.
> config: support lable ok-to-test on test-prod

- prow/config/external_plugins_config.yaml
Support to remove label needs-ok-to-test on tidb-operator & tidb. Afterwards, you can remove the relevant tags using the following command `/remove-label needs-ok-to-test`
> config: support add & remove label needs-ok-to-test on tidb-operator

- prow/config/plugins.yaml
- Currently no delicated release team in PingCAP.
- Triage should be finished by triage owners rather than "release team".
Close #925
> fix(prow/config): fix comment template of `cherry_pick_unapproved` plugin

- prow/config/config.yaml
Issue Number: ref pingcap/tidb#41241
How it Works:
> config(tidb): prioritize the PRs with `Priority/P*` labels in merging queue

- prow/config/external_plugins_config.yaml
We are planning to focus on MariaDB upstream when migrating data to TiDB, add this issue label to better organize MariaDB-related issues
> Add a "MariaDB" label for tiflow repo

- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
1. Add the `2024–tidb-docs-dash` label for the [pingcap/docs-cn](https://github.com/pingcap/docs-cn) and [pingcap/docs](https://github.com/pingcap/docs) repository. 
2. Support adding this label to a PR or issue by adding `/label 2024–tidb-docs-dash" in a comment of that PR or issue.
> docs-cn/docs: add the "2024–tidb-docs-dash" label

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Disable the bot's automatic "need-cherry-pick" label to avoid too many PRs being created automatically. The related behavior will be moved to tirelease, where users can manually operate or use bot commands to add the "need-cherry-pick" label and create PRs as needed.
The PR is just for test
--------
The actions after adding the "need-cherry-pick" label remain the same, but the bot will no longer automatically add the label. However, if the user adds the "need-cherry-pick" label by other means, the bot will still create the corresponding PR as before, and its behavior will remain unchanged.
> add: close test-repo need-cherry-pick label

- prow/config/config.yaml
set 'pull-verify' as required status on docs & docs-cn repos.
Currently, a bug in the judgment of "tide" has been discovered on doc & docs-cn repo. In the case of a failed pull-verify, tide may not be able to perceive the failure status, causing the PR to enter the merge queue.
> config: set 'pull-verify' as required status on docs & docs-cn

- prow/config/plugins.yaml
tidb-test add plugin lifecycle to support close and reopen issue or PR by comments.
example:
> /close
it will request the bot to close the PR or issue, but the comment sender should be the PR/issue author or repo collaborator.
> config: tidb-test add plugin lifecycle

- prow/config/labels.yaml
the wrong format make the cron job failed.
Issue Number: ref #1005 
fix wrong value introduced by #1005
How it Works:
> fix(prow/config): fix the color value for label `2024-tidb-docs-dash`

- prow/config/external_plugins_config.yaml
Issue Number: ref https://github.com/ti-community-infra/configs/discussions/1030 
The plugin is enabled, we must fill the config.
fill the config for `pingcap/monitoring` repository.
How it Works:
> fix(pingcap/monitoring): fill the cherry-pick config

- prow/config/config.yaml
- prow/config/plugins.yaml
remove tikv tide required context because all context already set required in branch protect rules.
> config: remove tikv tide required context

- prow/config/config.yaml
The tiflash master branch has enabled  new pipeline, so we need to update the required context.
> config(tiflash): update required contect on tiflash master

- prow/config/config.yaml
As https://github.com/tikv/pd/pull/6626 added 3 more chunks in the PD GitHub Actions workflow, this PR adopted this change for the release branches after release 7.3.
> config(pd): update pd-release-branch-pt to the correct chunk number

- prow/config/external_plugins_config.yaml
Currently, only tidb/pd has the prefix epic, and it is necessary to add the prefix epic to tikv/tiflow/tiflash as well.
> To add the prefix "epic" to tikv/tiflow/tiflash.

- prow/config/config.yaml
avoid prow's "Merging to branch *** is forbidden" on 8.2
> config: avoid prow's "Merging to branch *** is forbidden" on 8.2

- prow/config/config.yaml
avoid prow's "Merging to branch *** is forbidden" on 8.2 on some repos.
> config: avoid prow's "Merging to branch *** is forbidden" on 8.2 

- prow/config/config.yaml
As https://github.com/tikv/pd/pull/8342/files#diff-b299e538db88efad9dcf6937f6e10a31ba9d0edc04f843b471dcbccaee78da53R34-R48 added more chunks in the PD GitHub Actions workflow, this PR adopted this change for the release branches after release 8.3.
- release 8.2 code freeze at 6.28, so need to keep behavior
> config(pd): update pd-release-branch-pt-with-tools-chunks

- prow/config/config.yaml
Add config for tidb-engine-ext required context by tide, use the default context inherited from branch protection.
> config(pingcap/tidb-engine-ext): set tidb-engine-ext required context by tide

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
We have refactored the CI tasks to support pre-merge.
How it Works:
> chore(pingcap/tidb-tools): no need `ti-community-tar` plugin

- prow/config/config.yaml
disable the "keep update with base branch" option for master branch in branch protection rule.
why:
1. the major CI job `pull-unit-test` will pre merge the code before run the tests, it will ensure the quality before merging.
> fix(tikv/pd): update branch protection rule for `master`

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Issue Number: ref #824 
How it Works:
> feat(tikv/rocksdb,tikv/rust-rocksdb): enable bot to control the reviewing flow

- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
- unified the colors for cherry-pick labels.
- add missed labels for document repos.
How it Works:
> fix(prow/config): fix labels for doc repos

- prow/config/config.yaml
change for the branches:
- release-8.5
- release-8.4
- release-8.3
- release-8.2
- release-8.1
- release-7.5
- release-7.1
- release-6.5
How it Works:
No need to add the required status checks for unit test job, because
the unit test job will be triggered by prow. It will check the results
before merge it.
> fix(tikv/tikv): update branch protections

- prow/config/config.yaml
Currently, the ticdc repository does not require all GitHub Action tasks to run, so adjustments are being made to the configuration here.
> config(tiflow): ticdc skip-unknown-contexts

- prow/config/config.yaml
Make build and ut as required contexts.
> config(ticdc): add build and ut as required context

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
This pull request includes changes to the `prow/config/external_plugins_config.yaml` file to add configuration for the `pingcap/ticdc` repository. The most important changes are:
Configuration updates for `pingcap/ticdc` repository:
* Added `maintain_versions` with version "9.0".
* Added `wontfix_versions` with versions "9.0", "9.1", and "9.2".
* Added `affects_label_prefix` and `may_affects_label_prefix`.
* Added `linked_issue_needs_triage_label` and `need_cherry_pick_label_prefix`.
* Added `status_target_url` for triage completion check.
> fix(pingcap/ticdc): add config for issue-triage plugin

- prow/config/config.yaml
Remove some required statuses from the ticdc GitHub actions, as these tasks have been taken over by Prow. Tide will ensure that PRs are merged after the Prow jobs pass.
> config(ticdc): update required status

- prow/config/config.yaml
This pull request includes several updates to the `prow/config/config.yaml` file, focusing on branch protection, deck configuration, and tide configuration. The most important changes are grouped by their themes as follows:
Branch protection:
* Modified the `release-5.1` branch to ensure it remains protected and adjusted the indentation for better readability.
* Removed an unnecessary blank line in the configuration for `release-7.4` and `release-8.0` branches.
Deck configuration:
* Simplified the `job_url_template` by consolidating it into a single line.
Tide configuration:
* Added configurations for `pingcap-inc/enterprise-extensions` and `pingcap-inc/enterprise-plugin` repositories to include title and body templates for tide.
> fix(pingcap-inc/*): add merging templates for enterprise repos

- prow/config/config.yaml
This change will make Tide check whether the unit tests pass for the tikv/client-go repo, and the status of integration tests will not affect PR merges.
> config(tikv/client-go): add additional required status checks for branch protection and update client-go settings

- prow/config/config.yaml
- prow/config/plugins.yaml
Add trigger plugin on tikv/copr-test, support for triggering prow job tasks after migration.
> config(tikv/copr-test): add trigger plugin on tikv/copr-test

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
The core presubmit jobs for `tiflash` repo were refactored to prow style job, it will pre merge the codes before building or testing. So no need to enable the plugin to update branch for pull requests periodically in `tiflash` repo.
> opt(tiflash): disable tars plugin

- prow/config/plugins.yaml
This pull request includes a minor update to the `plugins.yaml` configuration file for the `approve` plugin. It removes a comment about the `tikv` organization repositories not being migrated, as it is no longer relevant.
> chore(prow/config): remove stale comments in plugins.yaml

- prow/config/config.yaml
Ref  https://github.com/PingCAP-QE/ci/pull/3744.
The new v2 pull-e2e pipeline is now in effect.
> config(tidb-operator): remove jenkins-ci / pull-e2e-kind-v2 from branch protection checks

- prow/config/external_plugins_config.yaml
- prow/config/labels.yaml
This pull request updates label configurations for several repositories to improve consistency and add support for the new `nextgen` label. The main changes include adding the `nextgen` label to the global label set, updating its usage in the `ti-community-label` plugin configuration, and reorganizing the order of additional labels to improve readability and maintainability.
Label additions and updates:
* Added the `nextgen` label to the global label configuration in `labels.yaml`, with a description and color for issues and PRs related to the nextgen kernel architecture.
* Included the `nextgen` label in the `ti-community-label` plugin configuration for relevant repositories, both as a required label and in the list of additional labels. …
> chore(prow/config): add nextgen label and update external plugins config
