ti-community-infra/configs

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
> config: add whileTrue0x90 as tidb-community-bots team member

- prow/config/config.yaml
This account for prow dev test.
> config: add rustin-bot be a team member

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Enable prow bot for tiup.
Welcome aboard 🎊
> config: enable prow for tiup

- prow/config/config.yaml
remove travis-ci, ref https://github.com/tikv/pd/pull/3194/
Signed-off-by: nolouch <nolouch@gmail.com>
> config: remove travis-ci

- prow/config/config.yaml
Signed-off-by: Zheng Xiangsheng <hundundm@gmail.com>
require `statics` check in pd, ref [tikv/pd#3194](https://github.com/tikv/pd/pull/3194)
> config: require statics check in pd

- .prow.yaml
- README.md
- go.mod
- orgs/tidb-community-bots/collaborators/teams.yaml
- prow/cluster/label_sync.yaml
- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.yaml
- prow/config/plugins.yaml
> chore: rename prow-configs to configs

- prow/config/plugins.yaml
/hold 
Waiting @lucklove review.
> config: enable lifecycle for tiup

- prow/cluster/label_sync.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.yaml
- prow/config/plugins.yaml
/hold 
Waiting the pd team review.
> config: enable label plugins for pd

- prow/config/plugins.yaml
enable hold and wip for tikv pd repo.
> config: enable hold and wip for tikv pd repo

- prow/config/external_plugins_config.yaml
add qa-release-merge as a trusted team for the pd release branch.
> config: add qa-release-merge as a trusted team for the pd release branch

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> chore: enable label plugin for tikv

- prow/config/config.yaml
close https://github.com/ti-community-infra/ti-community-prow/issues/255
> config: add merge_commit_template for tikv

- prow/config/config.yaml
> Revert "config: add merge_commit_template for tikv (#102)"

- orgs/config_test.go
- orgs/ti-community-infra/bots-test/teams.yaml
- orgs/ti-community-infra/org.yaml
- prow/config/external_plugins_config.yaml
close https://github.com/ti-community-infra/ti-community-prow/issues/195
> chore: rename bot

- prow/config/external_plugins_config.yaml
cc: https://github.com/ti-community-infra/tichi/issues/248
> config: Remove LGTM autoresponder for tikv repo 

- .prow.yaml
close https://github.com/ti-community-infra/configs/issues/60
> ci: add pull-configs-validate-orgs job

- ti-community-bots/dev/cluster/ing_ingress.yaml
> config: add ingress

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
close https://github.com/ti-community-infra/configs/issues/147
> config: enable tichi for tidb

- prow/config/config.yaml
> config: set empty commit body for tidb

- prow/config/external_plugins_config.yaml
cc: https://github.com/pingcap/tidb/pull/22872
> config: fix label blocker issue

- prow/jobs/ti-community-infra/org/lifecycle-periodics.yaml
Closing issues is too annoying, so we stop closing issues.
> config: stop close ti-community-infra issues

- prow/config/config.yaml
Signed-off-by: HunDunDM <hundundm@gmail.com>
* replace `idc-jenkins-ci-pd/integration-lightning-test` with `idc-jenkins-ci-pd/integration-br-test` in pd
> config: replace lightning-test with br-test in pd

- prow/config/config.yaml
Signed-off-by: HunDunDM <hundundm@gmail.com>
* config: add branch-protection to the release branch of PD
* config: add context_options to the release branch of PD
> config: add branch-protection and  context_options to the release branch of PD

- prow/config/config.yaml
Signed-off-by: HunDunDM <hundundm@gmail.com>
* config: use the union method config
> config: use the union method config for PD

- prow/config/config.yaml
delete by https://github.com/ti-community-infra/configs/pull/178
> config: fix tidb merge method

- prow/config/config.yaml
Signed-off-by: JmPotato <ghzpotato@gmail.com>
* config: add branch-protection to the release-5.0 branch of PD
* config: add context_options to the release-5.0 branch of PD
* config: format the file
> config: add branch-protection and context_options to the release-5.0 branch of PD

- prow/config/config.yaml
> config: cancel freeze release-4.0 for tidb/tikv

- prow/jobs/ti-community-infra/tichi/tichi-periodics.yaml
Part of ti-community-infra/tichi#317
> config: enable autobump for tichi

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
part of https://github.com/ti-community-infra/configs/issues/173
> config: enable tichi for dumpling

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
part of https://github.com/ti-community-infra/configs/issues/173
> config: enable tichi for dm

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Part of https://github.com/ti-community-infra/configs/issues/173
> config: enable tichi for tidb-tools

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
part of https://github.com/ti-community-infra/configs/issues/173
> config: enable tichi for ticdc

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
close https://github.com/ti-community-infra/configs/issues/173
> config: enable tichi for br

- prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-postsubmits.yaml
- prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-presubmits.yaml
We'll add these tasks and leave the GitHub actions in place for now, and add codecov and remove GitHub actions after we've made sure they're okay.
cc: https://github.com/ti-community-infra/ti-community-bot/issues/275
> ci: add ti-community-bot jobs

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
close https://github.com/ti-community-infra/configs/issues/110
> config: enable tichi for chaos-mesh/chaos-mesh

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Remove this response on April 1.
> config: disable ti-community-autoresponder for tidb

- prow/config/plugins.yaml
@bb7133 Request a feature that allows contributors without write access to modify the title.
> config: enable retitle for tidb

- prow/config/external_plugins_config.yaml
> config: add sig prefix for docs sig repos

- prow/jobs/ti-community-infra/tichi/tichi-periodics.yaml
part of https://github.com/ti-community-infra/tichi/issues/317
> config: make auto bump once a week

- prow/config/labels.yaml
- prow/config/plugins.yaml
- Add SIG labels for 4 docs repos.
- Delete some outdated labels.
- Add description for all labels.
> config: add labels for 4 docs repos

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Enable contribution plugin, which will add `contribution` or `first-time-contributor` labels to PR accordingly.
> config: enable contribution for docs sig

- prow/jobs/ti-community-infra/configs/configs-periodics.yaml
close https://github.com/ti-community-infra/tichi/issues/317
> ci: add configs-periodics.yaml

- prow/cluster/ti_community_tars_deployment.yaml
> build: Revert "config: set tars update period to 2h (#256)"

- prow/config/config.yaml
> config: remove unrequired status of tidb/tikv/pd

- prow/cluster/deck_deployment.yaml
- prow/cluster/hook_deployment.yaml
- prow/cluster/ing_ingress.yaml
- prow/cluster/ti-community-cherrypicker_deployment.yaml
- prow/cluster/ti_community_autoresponder_deployment.yaml
- prow/cluster/ti_community_blunderbuss_deployment.yaml
- prow/cluster/ti_community_contribution_deployment.yaml
- prow/cluster/ti_community_label_blocker_deployment.yaml
- prow/cluster/ti_community_label_deployment.yaml
- prow/cluster/ti_community_lgtm_deployment.yaml
- prow/cluster/ti_community_merge_deployment.yaml
- prow/cluster/ti_community_owners_deployment.yaml
- prow/cluster/ti_community_tars_deployment.yaml
- prow/cluster/tichi_web_deployment.yaml
close https://github.com/ti-community-infra/configs/issues/6
> build: support auto redirect

- prow/config/external_plugins_config.yaml
- prow/config/labels.yaml
- prow/config/plugins.yaml
part of  https://github.com/ti-community-infra/configs/issues/275
> config: enable cherrypicker for pd

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
part of https://github.com/ti-community-infra/configs/issues/278
> config: enable cherrypicker for ticdc

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
part of https://github.com/ti-community-infra/configs/issues/278
> config: enable cherrypicker for dm

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
close https://github.com/ti-community-infra/configs/issues/278
> config: enable cherrypicker for br

- prow/config/external_plugins_config.yaml
Signed-off-by: Cadmus <CadmusJiang@gmail.com>
> config: enable cherry-pick-approved label to lonng

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Enable cherry-pick-unapproved for forced frozen repos
> config: Enable cherry-pick-unapproved for forced frozen repos

- prow/config/external_plugins_config.yaml
- prow/config/labels.yaml
- prow/config/plugins.yaml
close https://github.com/ti-community-infra/configs/issues/279
> config: enable cherrypicker for docs-dm and docs-tidb-operator

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
close https://github.com/ti-community-infra/configs/issues/297
> config: br not require every PR to use the latest base

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
close https://github.com/ti-community-infra/configs/issues/289
> config: enable tichi for chaos-mesh/website

- prow/config/config.yaml
- prow/config/plugins.yaml
part of ti-community-infra/tichi#395
> config: enable release-note for pd

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.yaml
- prow/config/plugins.yaml
Enable blockade and label for chaos-mesh/website and chaos-mesh/website.
> config: enable blockade and label for chaos-mesh/website and chaos-mesh/website

- prow/config/external_plugins_config.yaml
Update the reviewer of Chaos Mesh with `include_reviewers`
> chore: update the reviewer of chaos-mesh

- prow/config/config.yaml
fit https://github.com/pingcap/dm/pull/1679
> config: remove some slow check from "Required"

- prow/config/config.yaml
> config: cleanup check_release_note CI config for pd

- prow/config/config.yaml
remove several required check in ticdc release-5.0 temporally
> config: remove several required check in ticdc release-5.0

- prow/config/config.yaml
- prow/config/plugins.yaml
part of ti-community-infra/tichi#395
Signed-off-by: Cadmus <CadmusJiang@gmail.com>
> config: enable release-note for tikv && cleanup check_release_note CI config for tikv

- prow/config/external_plugins_config.yaml
- prow/config/labels.yaml
Signed-off-by: qiancai <qqzczy@126.com>
> config: Add the v5.1 label for the docs-cn and docs repos

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Signed-off-by: tison <wander4096@gmail.com>
ref https://github.com/ti-community-infra/tichi/pull/562
> config: auto respond to lgtm

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
add release 5.1 config for:
- pingcap/tidb
- tikv/tikv
- tikv/pd
- pingcap/br
- pingcap/tidb-tools
- pingcap/ticdc
- pingcap/dumpling
>  config: add release 5.1 config

- prow/config/config.yaml
ref https://github.com/ti-community-infra/ti-community-bot/pull/373
> config: do not protect ti-community-infra master branch

- prow/config/config.yaml
integration test ci will be triggered when pr merged. Remove commit required contexts of integration-test
> config: remove integration test contexts check

- orgs/ti-community-infra/maintainers/teams.yaml
- orgs/ti-community-infra/sig-community-infra/teams.yaml
> config: add test-prod config for sig-community-infra

- prow/config/external_plugins_config.yaml
ref: https://github.com/tikv/community/pull/122
> config: make pd and tikv use github permission

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
>  config: enable tichi for pingcap/tidb-binlog

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> config: require  branchs up-to-date and enable tars plugin for br

- prow/cluster/ti_community_autoresponder_deployment.yaml
- prow/cluster/ti_community_blunderbuss_deployment.yaml
- prow/cluster/ti_community_cherrypicker_deployment.yaml
- prow/cluster/ti_community_contribution_deployment.yaml
- prow/cluster/ti_community_label_blocker_deployment.yaml
- prow/cluster/ti_community_label_deployment.yaml
- prow/cluster/ti_community_lgtm_deployment.yaml
- prow/cluster/ti_community_merge_deployment.yaml
- prow/cluster/ti_community_owners_deployment.yaml
- prow/cluster/ti_community_tars_deployment.yaml
- prow/cluster/tichi_web_deployment.yaml
- prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
- feat: return review notification by update comment (Fixed issue: https://github.com/ti-community-infra/tichi/issues/610)
> build: bump ti plugin version to v1.7.1

- prow/config/config.yaml
cc: https://github.com/pingcap/ticdc/pull/2402
> config: remove lint requirement for ticdc

- prow/config/external_plugins_config.yaml
Add me to the auto-cc list.
ref: https://github.com/pingcap/community/pull/508
> config(ticdc): Add me to the auto-cc list

- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Signed-off-by: qiancai qqzczy@126.com
> config: Add the v5.2 label for the docs-cn and docs repos

- prow/config/config.yaml
extension of https://github.com/ti-community-infra/configs/pull/394
The tests for release branches are not updated yet and some PRs are blocked.
> config(dumpling): update dumpling integration test requirements for release branches

- orgs/ti-community-infra/org.yaml
- orgs/ti-community-infra/sig-community-infra/teams.yaml
I'm retiring from ti-community-infra because I don't have time to continue helping review pr these days. Thanks!
> config: Retire from ti-community-infra

- prow/config/config.yaml
extension of #397 
the conficts was resloved and we can turn on this test requirements now
> config(dumpling): update dumpling integration test requirements

- prow/config/config.yaml
> config(tics): set tide context to required

- prow/config/labels.md
- prow/config/labels.yaml
config: add label for sig/bigdata for doc repos
> config: add label for sig/bigdata for doc repos

- prow/config/config.yaml
> config(tidb): remove check-license from release branch

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
According to the discussion results in：https://internals.tidb.io/t/topic/374/2
> config(tidb): enable blockade for tidb repo

- prow/config/config.yaml
* replace parser current circle ci by jenkins verify ci
> config(parser): replace circle ci by  jenkins verify ci 

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
close https://github.com/ti-community-infra/configs/issues/443
enable plugins:
- welcome
- assign
- hold
- wip
- size
- require-matching-label
- lifecycle
- retitle
- override
- ti-community-lgtm
- ti-community-merge
- ti-community-owners
- ti-community-label
- ti-community-label-blocker
- ti-community-contribution
Refer: https://book.prow.tidb.io/#/
> config: deploy tichi for dev-guide repo

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Signed-off-by: Qiang Zhou <zhouqiang.cl@gmail.com>
> config: add new branch release-5.3

- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
add new label for ticdc.
- area/dm
- area/ticdc
cc: https://github.com/pingcap/ticdc/issues/3175
> config(ticdc): add new label for ticdc

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> config: enable cherrypicker for test-plan repo

- prow/config/external_plugins_config.yaml
> config: add found/* label for tidb/tikv/pd/tiflash/tics

- prow/config/config.yaml
* modify tics integration-test required label
> config(tics): modify integragion-test label

- prow/config/config.yaml
Set pull as required check in docs-cn and docs.
> config: set pull as required check in docs-cn and docs

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
- prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
Signed-off-by: xiang <xiang13225080@163.com>
> config: add chaos-mesh/chaosd

- prow/config/external_plugins_config.yaml
> config: set ran-huang as default reviewer for docs-tidb-operator

- prow/config/labels.md
- prow/config/labels.md.tmpl
- prow/config/labels.yaml
Add a `type/compatibility-or-feature-change` label for docs-tidb-operator.
> config(docs-tidb-operator): add a label for type/compatibility change

- prow/config/external_plugins_config.yaml
config: add shichun-0415 to docs default reviewer
> config: add shichun-0415 to docs default reviewer

- prow/config/external_plugins_config.yaml
> config: set shichun-0415 as default reviewer for docs-dm

- prow/config/external_plugins_config.yaml
Signed-off-by: xiang <xiang13225080@163.com>
https://github.com/chaos-mesh/chaos-mesh/pull/2036
> config: add `shivanshs9` as reviewer of Chaos Mesh

- prow/config/config.yaml
ref: https://github.com/ti-community-infra/configs/pull/486
> config: only use the new commit message template for specify repos

- prow/config/config.yaml
Signed-off-by: cwen0 <cwenyin0@gmail.com>
> config: update chaos-mesh website repo

- prow/config/external_plugins_config.yaml
ref https://github.com/pingcap/community/pull/620
> config: add migration team as tidb repo owners  to handle br package

- prow/config/labels.md
- prow/config/labels.yaml
> config(ticdc): add new label for apis

- prow/config/config.yaml
* tidb add `idc-jenkins-ci-tidb/mysql-test` required label
> config: tidb add mysql-test required label

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
part of https://github.com/tikv/community/issues/160
> config: disable the format checker on tikv and pd

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
> config: add new branch release-5.4

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
This reverts commit 52c6402a7b0ea466f96f822fdba04b978498b4fc.
> revert: Revert "config: don't add the do-not-merge label temporarily (#499)"

- prow/config/labels.md
- prow/config/labels.yaml
> config: add component/owner label to tiflow repo

- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
> config: add format-checker skip label for tidb repos

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
part of https://github.com/tikv/community/issues/161
> config: apply new tide template for tikv repos

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
config: add release-5.4 branch config for docs repos
> config: add release-5.4 branch config for docs repos

- prow/config/config.yaml
https://regex101.com/r/2pBTI5/1
> fix: use lazy mode to match commit message block

- prow/config/config.yaml
Signed-off-by: JmPotato <ghzpotato@gmail.com>
> config: update the PD required_status_checks

- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Add v6.0 label to docs/docs-cn repos
> config: add v6.0 label to docs repos

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> config: enable tichi for tispark

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Signed-off-by: Schrodinger ZHU Yifan <i@zhuyi.fan>
Renaming tics to tiflash in related configs
> config: rename tics to tiflash

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
> config: add release-6.0

- prow/config/config.yaml
Signed-off-by: JmPotato <ghzpotato@gmail.com>
> config: update the PD required-contexts for release-6.0

- prow/config/config.yaml
Signed-off-by: SchrodingerZhu <i@zhuyi.fan>
> config: enforce CLA checking for tiflash

- prow/config/config.yaml
Reverts ti-community-infra/configs#545
> config: Revert "config: enforce CLA checking for tiflash"

- prow/config/config.yaml
> config: add release 6.0 branch config for docs repo

- prow/config/external_plugins_config.yaml
Related to https://github.com/pingcap/community/pull/645
cc: @purelind @zhangyangyu
> config: add tiflash teams for owners config

- prow/config/config.yaml
* set ut as required status for tiflash release branch
> config(tiflash): set tiflash ut as required status for release branch

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
config: set the docs-tiem branch of docs-cn as protected
> config: set the docs-tiem branch of docs-cn as protected

- prow/config/config.yaml
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>
> add required to realtikv-test on tidb

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
> config: add release-6.1 branch config

- prow/config/external_plugins_config.yaml
* add missing label in release-6.1
> config: add missing release-6.1 labels

- orgs/ti-community-infra/community-infra-reviewers/teams.yaml
- orgs/ti-community-infra/config-reviewers/teams.yaml
- orgs/ti-community-infra/org.yaml
@purelind will help TiDB community review the PR changed ti-chi-bot config.
> config: join purelind as ti-community-infra reviewer

- prow/config/config.yaml
ci stuck in pr https://github.com/chaos-mesh/chaosd/pull/158
> config: update config.yaml for chaos-mesh/chaosd

- prow/config/config.yaml
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
https://github.com/chaos-mesh/chaos-mesh/pull/3177#issuecomment-1135336365 will add arm64 test for the chaos-mesh
> add arm64 test for Chaos Mesh

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
* support tiflash feature branch: https://github.com/pingcap/tiflash/tree/planner_refactory
> tiflash: support tiflash feature branch planner_refactory

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
Reverts ti-community-infra/configs#565
> Revert "config: set the docs-tiem branch of docs-cn as protected"

- prow/config/config.yaml
> config(docs): add release 6.1 branch config for docs repos

- orgs/ti-community-infra/community-infra-committers/teams.yaml
- orgs/ti-community-infra/config-reviewers/teams.yaml
- orgs/ti-community-infra/org.yaml
> config: invite @wuhuizuo joining the infra team

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> config: enable tichi for `pingcap/tiunimanager` and `pingcap/tiunimanager-ui`

- prow/config/config.yaml
* parse has been moved to pingcap/tidb, remove ci check.
> config: remove parse repo ci check

- prow/config/config.yaml
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>
> *: remove real tikv

- prow/config/external_plugins_config.yaml
config: remove tomshawn from the auto reviewer of the docs repo
> config: remove tomshawn from the auto reviewer of docs repo

- prow/config/config.yaml
Related PR: 
master: https://github.com/pingcap/docs/pull/9354
v5.4: https://github.com/pingcap/docs/pull/9349
v6.1: https://github.com/pingcap/docs/pull/9353
> config: update the status checks for the pingcap/docs repository 

- prow/config/plugins.yaml
- enable plugins: `milestone` and `milestoneapplier`.
- config plugin configuratioins.
How it Works:
> config(tikv/tikv): auto apply to milestone for new pull request

- prow/config/external_plugins_config.yaml
config: add shichun-0415 as the auto reviewer of docs-cn
> config: add shichun-0415 as the auto reviewer of docs-cn

- orgs/ti-community-infra/bots-test/teams.yaml
- orgs/ti-community-infra/community-infra-reviewers/teams.yaml
- orgs/ti-community-infra/maintainers/teams.yaml
- orgs/ti-community-infra/org.yaml
- add @wuhuizuo into maintainer team.
- add @wuhuizuo and his bots into reviewer team.
- add @wuhuizuo and his bots into `bots-test` team.
> config(ti-community-infra): add @wuhuizuo and his bots to teams

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
* enable ci context check for ticdc feature branch cli-use-open-api
refer https://github.com/ti-community-infra/configs/pull/580
> config(tiflow): support feature branch check

- prow/config/external_plugins_config.yaml
enabled:
- rebase method
- squash method
Ref issue #597
> config(pingcap/tiflash): enable comment to set merge method for tiflash

- prow/config/config.yaml
Reverts ti-community-infra/configs#605
> Revert "Feature/protect for hotfix branch"

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- ref https://github.com/pingcap/tiflash/issues/4739
- revert https://github.com/ti-community-infra/configs/pull/580
- tiflash feature branch: https://github.com/pingcap/tiflash/tree/planner_refactory
- wait for https://github.com/pingcap/tiflash/pull/5493 merged
> tiflash: remove tiflash feature branch planner_refactory

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
support tidb feature branch: https://github.com/pingcap/tidb/tree/distribute-reorg
> prow/config: support tidb feature branch distribute-reorg

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Signed-off-by: xhe <xw897002528@gmail.com>
> config: check invalid title for tidb

- prow/config/external_plugins_config.yaml
Signed-off-by: xhe <xw897002528@gmail.com>
> configs: missed regexp for title

- prow/config/external_plugins_config.yaml
Signed-off-by: xhe <xw897002528@gmail.com>
> prow/config: update wontfix verion for tidb/tikv

- prow/config/config.yaml
Ref https://github.com/pingcap/tidb/pull/37235
> prow: use new github actions as required status

- .github/ISSUE_TEMPLATE/deploy-request.md
- README.md
- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.md.tmpl
- prow/config/plugins.yaml
replaces:
- `prow.tidb.io` to `prow.tidb.net`
- `book.prow.tidb.io` to `book.prow.tidb.net`
How it Works:
> chore(prow/config): update domain name

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Problem Summary: add prow configuration for new release `v6.3`
How it Works:
> feat: add config for new release v6.3

- prow/config/labels.yaml
> fix(config): color values with quotes to avoid `+Inf` invalid errors

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
Signed-off-by: STRRL <im@strrl.dev>
> feat: new branch for chaos mesh release-2.4

- prow/config/external_plugins_config.yaml
Config versions for each repo corresponding to https://pingcap.feishu.cn/wiki/wikcnE3AzEPf9flPeUKAQf6JJRf?table=tblzkP0HhzSXZ2dw&view=vewzeqCJf6
> Config(cp): add versions to won't fix list

- prow/config/external_plugins_config.yaml
config: remove shichun-0415 as the auto reviewer of docs-cn
> config: remove shichun-0415 as the auto reviewer of docs-cn

- scripts/update-labels.sh
optimize speed for local development
How it Works:
> chore(scripts): optimize update-labels.sh to avoid clone repo multi times

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
> config: add release-6.4 branch config

- prow/config/plugins.yaml
- to debug refactoring mergeCI pipelines
How it Works:
> config(pingcap/tidb): forward `pull_request` github event to staging jenkins CI

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
Signed-off-by: STRRL <im@strrl.dev>
> feat: update prow config for chaos-mesh with new branch release-2.5

- prow/config/external_plugins_config.yaml
Why: avoid to trigger CI builds duplicately
How it Works:
> config: update comment template of tar plugin

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
> config: add release-6.5 branch config

- prow/config/external_plugins_config.yaml
Reverts ti-community-infra/configs#697
> Revert "config: update comment template of tar plugin" in tiflash repo

- prow/config/config.yaml
> config(tichi): decide the required contexts by prow tide

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> chore(test-prod): disable tars plugin

- prow/config/plugins.yaml
> feat(tidb): forward webhook event to product jenkins ci server

- prow/cluster/jenkins-operator-deployment.yaml
- prow/cluster/jenkins-operator-rbac.yaml
- prow/cluster/jenkins-operator-service.yaml
- prow/config/config.yaml
> feat(prow/cluster): add jenkins-operator component

- prow/config/config.yaml
> feat(test-prod): enable in_repo_config in test_prod repo

- prow/config/plugins.yaml
prow job depend on trigger plugin
How it Works:
> feat(test-prod): enable trigger plugin on test-prod

- prow/cluster/jenkins-operator-deployment.yaml
Ref issue: https://github.com/kubernetes/test-infra/pull/28314
> fix(configs/prow): fix jenkins job fetching

- prow/jobs/pingcap/tidb/tidb-presubmits.yaml
> feat(pingcap/tidb): add prow-jenkins jobs

- prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
> ci: bump checkconfig image

- prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Reverts ti-community-infra/configs#745
> Revert "ci: bump checkconfig image"

- prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Reverts ti-community-infra/configs#746
> Revert "Revert "ci: bump checkconfig image""

- prow/jobs/pingcap/tidb/tidb-presubmits.yaml
> chore(prow/jobs/pingcap/tidb): update wip jobs

- prow/jobs/pingcap/tidb/tidb-presubmits.yaml
> chore(prow/jobs/pingcap/tidb): enable job `build`

- prow/jobs/pingcap/tidb/tidb-presubmits.yaml
> chore(prow/jobs/pingcap/tidb): enable job `check`

- prow/jobs/pingcap/tidb/tidb-presubmits.yaml
> chore(prow/jobs/pingcap/tidb): enable job `check2`, `mysql-test`, `unit-test`

- prow/config/plugins.yaml
- prow/jobs/tikv/pd/pd-presubmits.yaml
> chore(prow/jobs/tikv/pd): add wip  presubmits jobs

- prow/jobs/tikv/pd/pd-presubmits.yaml
> chore(prow/jobs/tikv/pd): enable job `build`

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
- prow/jobs/pingcap/tidb/tidb-presubmits.yaml
How it Works:
depend on https://github.com/PingCAP-QE/ci/pull/1669
> chore(prow/jobs/pingcap/tidb): add jobs for branches release-6.[1-4]

- prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
but skip report currently for debuging
How it Works:
> chore(prow/jobs/pingcap/tidb): enable postsubmits job `e2e-test`

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Reverts ti-community-infra/configs#754
> Revert "chore(prow/jobs/pingcap/tidb): add jobs for branches release-6.[1-4]"

- prow/config/external_plugins_config.yaml
> fix(prow/config): add `release-6.5` to triage list

- prow/config/plugins.yaml
- prow/jobs/ti-community-infra/test-infra/test-infra-postsubmits.yaml
- prow/jobs/ti-community-infra/test-infra/test-infra-presubmits.yaml
> ci(ti-community-infra/test-infra): add jobs

- prow/jobs/pingcap/tidb/tidb-presubmits.yaml
> fix(prow/jobs/pingcap/tidb): fix trigger branches for hotfix branches

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> chore(prow/config): enable external plugin ti-*-cherry-pick on `pingcap/tidb-operator` repo

- prow/jobs/ti-community-infra/test-infra/test-infra-presubmits.yaml
- disable verify boilerplate
- disable verify yamllint
> ci(ti-community/test-infra): fix lint jobs

- prow/config/external_plugins_config.yaml
prefer to inner dns in cluster
> fix(prow/config): prefer to using in-cluster external dns

- prow/config/external_plugins_config.yaml
Reverts ti-community-infra/configs#770
> Revert "fix(prow/config): prefer to using in-cluster external dns"

- prow/cluster/tide_deployment.yaml
- prow/config/config.yaml
Currently test in test-prod repo
How it Works:
> fix(prow/cluster, prow/config): bump tide images and fix tide merge template

- prow/config/config.yaml
- org: tikv
- repos: pingcap/tidb, pingcap/tidb-tools, pingcap/tiflow, pingcap/tidb-binlog, pingcap/ng-monitoring
tested in dev env: https://github.com/ti-community-infra/test-dev/pull/541
tested in prod env: https://github.com/ti-community-infra/test-prod/pull/45
> fix(prow/config): fix tide merge templates

- prow/config/config.yaml
And combine repos with same query args
How it Works:
> fix(prow/config): add hotfix branche prefix to execlude branches for tide query

- prow/cluster/ti_community_autoresponder_deployment.yaml
- prow/cluster/ti_community_blunderbuss_deployment.yaml
- prow/cluster/ti_community_cherrypicker_deployment.yaml
- prow/cluster/ti_community_contribution_deployment.yaml
- prow/cluster/ti_community_format_checker_deployment.yaml
- prow/cluster/ti_community_issue_triage_deployment.yaml
- prow/cluster/ti_community_label_blocker_deployment.yaml
- prow/cluster/ti_community_label_deployment.yaml
- prow/cluster/ti_community_lgtm_deployment.yaml
- prow/cluster/ti_community_merge_deployment.yaml
- prow/cluster/ti_community_owners_deployment.yaml
- prow/cluster/ti_community_tars_deployment.yaml
- prow/cluster/tichi_web_deployment.yaml
> fix(prow/cluster): bump ti-community plugins with cherry pick invite fixing

- prow/config/config.yaml
Ref: unit test https://github.com/ti-community-infra/test-infra/pull/17
> chore(prow/config): test new merge template for repos in ti-community-infra org

- prow/config/config.yaml
- prow/jobs/ti-community-infra/test-prod/test-prod-presubmits.yaml
avoid include ci args in commit message
> fix(prow/config): update merge template for pingcap/tidb repo

- prow/config/config.yaml
- prow/config/plugins.yaml
- prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
- prow/jobs/pingcap/tidb/tidb-presubmits.yaml
- prow/jobs/tikv/pd/pd-presubmits.yaml
Reverts ti-community-infra/configs#788
> Revert "feat(prow/jobs): delete jobs for pingcap and tikv org"

- prow/config/plugins.yaml
> feat(prow/config): add config update file map for pingcap-qe/ci repo

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Also update branch protections for branches:
- master
- feature/*
- release-6.[1-5]
Now, the CI jobs run with pre merge mode for pull requests.
How it Works:
> fix(prow/config): disable tars plugin on pingcap/tidb repo

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
> config: add release-6.6 branch config

- prow/config/plugins.yaml
Enable trigger plugin for tidb-test repo.
> feat(pingcap/tidb-test): enable trigger plugin for tidb-test

- prow/config/labels.md
- prow/config/labels.yaml
Add missing lable for release-6.5 and release-6.4
> config: add missing label for release-6.5 and release-6.4

- prow/config/config.yaml
remove tiflash-scripts build ci for all branchs
> config(pingcap/tiflash-scripts): tiflash-scripts remove build-ci

- prow/config/config.yaml
> config: fix indent

- prow/config/config.yaml
- prow/config/plugins.yaml
Add repo pingcap-qe/artifacts.
> config: add repo pingcap-qe/artifacts

- prow/config/config.yaml
Add required status on tidb-test master.
> feat: add tidb-test required status

- prow/config/plugins.yaml
Add plugins to tidb-test:
* welcome
* assign
* hold
* wip
> config: add plugins to tidb-test

- prow/config/config.yaml
Reverts ti-community-infra/configs#801
> Revert "feat: add tidb-test required status"

- prow/config/config.yaml
> fix(prow/config): fix tide query config for repo `ti-community-infra/configs`

- OWNERS
- OWNERS_ALIASES
- prow/OWNERS
- prow/cluster/OWNERS
- prow/config/OWNERS
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
- prow/jobs/OWNERS
- scripts/OWNERS
> feat: add prow owner files

- prow/config/plugins.yaml
> fix(prow/config): fix plugin list url for approve plugin

- prow/config/config.yaml
Reverts ti-community-infra/configs#812
> Revert "chore(prow/config): delete prow job contexts in branch protection for tidb@master"

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
currently only enable cherry-pick feature.
usage doc: https://book.prow.tidb.net/#/plugins/cherrypicker
> feature(prow/config): enable cherry-pick plugin on `tikv/client-java` repo

- prow/config/config.yaml
- prow/config/plugins.yaml
> chore(prow/config): add repo pingcap-qe/benchbot

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Add release-7.0 branch config.
> config: add release-7.0 branch config

- prow/jobs/ti-community-infra/test-infra/test-infra-postsubmits.yaml
- prow/jobs/ti-community-infra/test-infra/test-infra-presubmits.yaml
> fix(prow/jobs/ti-community-infra/test-infra): fix prow jobs

- prow/config/plugins.yaml
> config: add trigger plugin to tiflow

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
currently it's not migrated from pingcap org, but the configuration we can setup before.
How it Works:
> chore(prow/config): add repo pingcap-qe/test-plan

- prow/config/config.yaml
- prow/config/plugins.yaml
- PingCAP-QE/automated-tests
- PingCAP-QE/endless
- PingCAP-QE/qa
- PingCAP-QE/test-infra
- PingCAP-QE/workload
How it Works:
> chore(prow/config): add repos in pingcap-qe

- prow/config/plugins.yaml
Add owners plugin to tidb-test.
> config: add owners plugin

- prow/config/config.yaml
Adjust some tilfow integration test required status in master branch.
> config(tiflow): remove some it required label

- prow/config/plugins.yaml
> fix(prow/config): fix cherry-pick config for pingcap-qe/test-plan

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> chore(prow/config): switch review plugins to lgtm + approve for repos in `ti-community-infra`

- .github/renovate.json
- .github/renovate.json5
> chore: update renovate config

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
- delete configuration for archived repo: `pingcap-docs-appdev`.
- fix repo name: `pingcap-inc/tiflash-scripts`, Since it's migrated into `pingcap-inc`. Currently it will broken the branch protection job.
How it Works:
> fix(prow/config): fix failure of branch protection cron job

- prow/config/plugins.yaml
Issue Number: close PingCAP-QE/ci#1968
How it Works:
> chore(prow/config): dispatch push event to jenkins-gitee for pingcap-qe/ci repo

- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
> chore(prow/config): delete useless labels and remove v4.0 and v5.0 from maintain versions

- prow/cluster/branchprotector.yaml
- prow/cluster/crier_deployment.yaml
- prow/cluster/deck_deployment.yaml
- prow/cluster/ghproxy.yaml
- prow/cluster/hook_deployment.yaml
- prow/cluster/horologium_deployment.yaml
- prow/cluster/jenkins-operator-deployment.yaml
- prow/cluster/label_sync.yaml
- prow/cluster/needs-rebase_deployment.yaml
- prow/cluster/prow_controller_manager_deployment.yaml
- prow/cluster/sinker_deployment.yaml
- prow/cluster/statusreconciler_deployment.yaml
- prow/cluster/tide_deployment.yaml
- prow/jobs/ti-community-infra/devstats-dev-guide/devstats-dev-guide-postsubmits.yaml
- prow/jobs/ti-community-infra/devstats-dev-guide/devstats-dev-guide-presubmits.yaml
- new builtin lgtm plugin but hacked with count feature.
How it Works:
> feat(prow/cluster): update prow deployment to new image

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> config(pingcap/tidb-test): enable cherry pick plugin

- prow/cluster/hook_deployment.yaml
fix ti-community-infra/configs#845
> deps(prow/cluster): bump hook image to v20230324-18d2952

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Add release-7.1 branch config.
> config: add release-7.1 branch config

- prow/config/kustomization.yaml
- prow/jobs/kustomization.yaml
- prow/kustomization.yaml
> feat(prow): kustomize config and jobs

- prow/config/kustomization.yaml
> fix(prow/config): fix kustomization file

- prow/config/config.yaml
> revert(prow/config): restore tide merge templates

- prow/config/config.yaml
> fix(prow/config): fix exscape in merge templates

- prow/config/config.yaml
- update branch protection for `pingcap/tiflow`: make PRs no need to update src branch before merge.
- `release-7.1` and  `master` branches
> fix(prow/config): update config for `pingcap/tiflow` about branch protection

- prow/config/config.yaml
- prow/config/plugins.yaml
> chore(prow/config): move out `pingcap-qe/artifacts` to another bot

- prow/config/plugins.yaml
- tidb: only dispatch comment event on pr
- test-infra: dispatch pull request events and comment events
> feat(prow/config): dispatch event to  chatgpt external plugin

- prow/config/plugins.yaml
Reviewer can let bot to reivew it with comment `/review default`
> feat(prow/config): dispatch event to chatgpt external plugin for `tikv/tikv` repo

- prow/config/plugins.yaml
Reverts ti-community-infra/configs#858
> Revert "feat(prow/config): dispatch event to chatgpt external plugin for `tikv/tikv` repo"

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
enable plugins like `pingcap/tidb-test`.
How it Works:
> feat(prow/config): add repo `pingcap-inc/enterprise-extensions`

- prow/config/config.yaml
- prow/config/plugins.yaml
new repos:
- `artifacts`
- `ee-apps`
- `ee-ops`
> feat(prow/config): add repos in `pingcap-qe` org

- prow/config/config.yaml
> config(prow/config): fix tide for release branches

- prow/config/labels.md
- prow/config/labels.yaml
- prow/config/plugins.yaml
> config(prow/config): disable `release-note` plugin for docs repos

- prow/config/plugins.yaml
> config(prow/config): fix external plugin forwards for tidb-operator

- prow/config/plugins.yaml
> config(prow/config): disable blunderbuss plugin and update approve config for docs repos

- prow/config/plugins.yaml
> config(prow/config): fix approve config for docs repos

- prow/config/plugins.yaml
Why: it's offline.
How it Works:
> config(prow/config): delete forwarding to prow-ee.pingcap.net

- prow/cluster/README.md
- prow/config/plugins.yaml
- prow/jobs/README.md
Why: now we use GitOps for ensure persistent.
How it Works:
> chore(prow/config): delete useless config fields

- prow/config/config.yaml
update required status on tiflow release-5.3.
> config(tiflow): update required status on tiflow release-5.3

- prow/config/kustomization.yaml
- prow/cronjobs/branch-protector.yaml
- prow/cronjobs/label-sync.yaml
> config(prow/cronjobs): add branch protect and label sync jobs

- prow/config/config.yaml
also make the include branch congfiguration more simpler
How it Works:
> config(prow/config): add release-3.* and release-4.* into tide's query branches for docs repos

- prow/config/external_plugins_config.yaml
> config(prow/prow): execlude old review labels when create cherry-pick PR

- prow/config/plugins.yaml
> config(prow/config): enable chatgpt external plugins for docs repo

- prow/cronjobs/branch-protector.yaml
- prow/cronjobs/label-sync.yaml
> fix(prow/cronjobs): fix github app id env var

- prow/config/external_plugins_config.yaml
> config(pingcap/tiflow): inherit `lgtm` label when create cherry-pick pull request

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
add release-7.2 branch config.
> config: add release-7.2 branch config

- prow/config/config.yaml
it is related with https://github.com/tikv/pd/pull/6626
> config: update the PD required-contexts

- prow/config/config.yaml
> config: correct indentation

- prow/config/external_plugins_config.yaml
> config(prow/config): exclude `cherry-pick-approved` label when create cherry-pick pull requests

- prow/config/config.yaml
currently allow PingCAP/EE team
Ref: https://github.com/PingCAP-QE/ci/issues/2221
> config(prow/config): add rerun auth configs

- prow/config/config.yaml
Ref: https://github.com/PingCAP-QE/ci/issues/2221
> config(prow/config): fix team slug for deck rerun auth configs

- prow/config/config.yaml
Reverts ti-community-infra/configs#928
> Revert "config(prow/config): update branch protection config for `pingcap/tidb` release branches"

- prow/config/config.yaml
Issue Number: ref https://github.com/PingCAP-QE/ci/issues/2129
update branch protect rules for release-6.1
How it Works:
* Prepare to enable condition triggering on CI jobs for efficiency.
* Now the jobs will be triggered by prow bot, we just need to keep tide in required context list.
* The feature has enabled in trunk branch for serval weeks, It's stable and correct.
* when it merged we need update the hot fix branch protection (by regex) manually
> config(prow/config): update branch protection config for pingcap/tidb release-6.1

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Enable plugins on `pingcap/tiproxy`.
> config(tiproxy): add repo pingcap/tiproxy config

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Repo names are case-sensitive.
> config(tiproxy): repo names are case-sensitive.

- prow/config/config.yaml
Reverts ti-community-infra/configs#931
> config(prow/config): update branch protection config for `pingcap/tidb` release branches

- prow/config/openai/tasks.yaml
- prow/config/plugins.yaml
> config(pingcap-qe/artifacts): forward events to tekton event listenser

- prow/config/openai/tasks.yaml
- prow/config/plugins.yaml
Ref: https://github.com/kubernetes/test-infra/issues/20631
How it Works:
> config(prow/config): migrate to new plugins configuration struct

- prow/config/plugins.yaml
> fix(pingcap-qe/artifacts): fix tekton external plugin

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
add release-7.3 branch config.
> config: add release-7.3 branch config

- prow/config/config.yaml
Reverts ti-community-infra/configs#945
> Revert "chore(pingcap/tidb): disable github review approve and codeowner required options"

- prow/config/openai/tasks.yaml
> chore(pingcap/*docs*): no automatic review on pull request which has `lgtm` labeled

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> replace TiProxy with tiproxy

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Reverts ti-community-infra/configs#953
> Revert "feat(pingcap/tidb): block mergeing for pull requests which have none finished test tasks"

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Reverts ti-community-infra/configs#954
> Revert "Revert "feat(pingcap/tidb): block mergeing for pull requests which have none finished test tasks""

- prow/config/plugins.yaml
> chore(prow/config): enable pr format checker plugon on test-prod repo

- prow/config/external_plugins_config.yaml
> chore(prow/config): enable pr format checker plugon on test-prod repo master branch

- prow/config/external_plugins_config.yaml
> chore(prow/config): fix pr format checker plugon on test-prod repo master branch

- prow/config/external_plugins_config.yaml
> fix(pingcap/tidb): pr format checker regex string

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> fix(pingcap-qe/tidb-test): rename `pingcap/tidb-test` to `PingCAP-QE/tidb-test`

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
Add prow bot service for `pingcap-inc/enterprise-plugin` repo.
> fix(pingcap-qe/tidb-test): add service for `pingcap-inc/enterprise-plugin` repo

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
add release-7.4 branch config.
> config: add release-7.4 branch config

- prow/config/config.yaml
> fix(pingcap/tidb): fix tide merge commit message template

- prow/config/plugins.yaml
- add forwarding as an external plugin for `pingcap` ORG.
How it Works:
- forward the events to tekton event listener.
> chore(prow/config): add event router to tekton cd for for pingcap org

- prow/config/plugins.yaml
> chore(prow/config): add event router to tekton cd for for tikv org

- prow/config/plugins.yaml
Issue Number: close #988 
How it Works:
> Support `pingcap/monitoring` repo

- prow/config/plugins.yaml
Reverts ti-community-infra/configs#991
> Revert "Add tirelease webhook of tikv/tikv"

- prow/config/config.yaml
the community pull requests need more votes and days.
> chore(pingcap/community): disable auto merge by bot

- prow/config/plugins.yaml
Reverts ti-community-infra/configs#993
> Revert "Update plugins.yaml"

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
> fix(tikv/tikv,tikv/pd): enable merging on `feature/*` branches

- prow/config/plugins.yaml
add plugins to tikv/migration.
> config: add plugins to tikv/migration

- prow/config/config.yaml
> chore(prow/configs): enable prioritize_existing_batches on `pingcap/tidb`

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Add release-7.6 branch configs.
> config: add release-7.6 branch configs

- prow/config/config.yaml
Reverts ti-community-infra/configs#1013
> Revert "chore(prow/configs): enable prioritize_existing_batches on `pingcap/tidb`"

- prow/config/config.yaml
- prow/config/plugins.yaml
> feat(pingcap/monitoring): use ti-chi-bot app to take over review control and automate merges

- prow/config/config.yaml
update docs & docs-cn required status.
> config(docs&docs-cn): update docs & docs-cn required status

- prow/cronjobs/label-sync.yaml
for debug which repo's configuration make the job failed.
How it Works:
> chore(prow/config): split the cron job to serval containers

- prow/config/labels.yaml
> fix(prow/config): fix the color value for label `2024-tidb-docs-dash`

- prow/cronjobs/label-sync.yaml
Reverts ti-community-infra/configs#1026
> Revert "chore(prow/config): split the cron job to serval containers"

- prow/config/external_plugins_config.yaml
> chore(prow/config): simple configuration for `ti-community-issue-triage` plugin

- prow/config/config.yaml
- prow/config/openai/tasks.yaml
- prow/config/plugins.yaml
> chore(prow/config): fix the configuration on repo branches

- prow/config/config.yaml
Ref: https://internals.tidb.io/t/topic/892
> fix(tikv/tikv): update branch protection rule

- prow/config/config.yaml
Reverts ti-community-infra/configs#994
> Revert "chore(pingcap/community): disable auto merge by bot"

- prow/config/external_plugins_config.yaml
Add release-1.6 for https://github.com/pingcap/docs-tidb-operator
> config(docs): add docs tidb operator release-1.6

- prow/config/plugins.yaml
add trigger plugin for tikv repo.
> config: add trigger plugin for tikv

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
Add release-8.1 branch configs.
> config: add config for branch release-8.1

- prow/config/config.yaml
update tikv ut required context.
> config(tikv): update tikv ut required context

- prow/config/config.yaml
Reverts ti-community-infra/configs#1043
> Revert "config(tikv): update tikv ut required context"

- prow/config/openai/tasks.yaml
- prow/config/plugins.yaml
Close #1050
User can request reviewing from bot with AI force:
`/review`
Then the bot will respond the review summary.
> REQUEST: deploy chatgpt plugin for pingcap/tiflow

- prow/config/config.yaml
Remove two required context on master, tide will handle required context.
> config(tiflash): remove two required context on master

- prow/config/plugins.yaml
> config(tikv/community): enable `trigger` plugin

- prow/config/config.yaml
> chore(pingcap/tiflash): update merge template

- prow/config/plugins.yaml
> fix(pingcap-qe/ci): skip collaborators for lgtm for ci.git

- prow/config/config.yaml
- prow/config/plugins.yaml
> change the prow configuration for `pingcap/tidb-engine-ext` repository.

- prow/config/config.yaml
- prow/config/plugins.yaml
Issue Number: close #1068 
How it Works:
> fix(tikv/*): enable DCO plugin

- prow/config/plugins.yaml
> fix(tikv/*): fix dco config

- prow/config/config.yaml
- prow/config/plugins.yaml
This reverts commit 22981bd3eee52ed172d07a1c1339822612ee8ec1.
How it Works:
> Revert "fix(tikv/*): enable DCO plugin (#1069)"

- prow/config/config.yaml
- prow/config/plugins.yaml
Reverts ti-community-infra/configs#1073
> Revert "Revert "fix(tikv/*): enable DCO plugin (#1069)""

- prow/config/config.yaml
Enable new tidb-tools pipelines. Related to this https://github.com/PingCAP-QE/ci/pull/3003.
> config: enable new tidb-tools pipelines

- prow/config/external_plugins_config.yaml
Add the "impact" prefix label to tidb/tikv/pd/tiflow/tiflash to indicate the impact of the bug.
> Add the prefix label impact to label the impact of the bug

- prow/config/config.yaml
remove unnecessary branch protect status, check-issue-triage-complete only exist on master branch.
> config(pingcap/tiflash): remove unnecessary branch protect status

- prow/config/external_plugins_config.yaml
- prow/config/labels.md
- prow/config/labels.yaml
> delete found/customer and found/community, and add report/customer and report/community

- prow/config/plugins.yaml
> feat(tikv/raft-engine): enable trigger and common plugins

- prow/config/plugins.yaml
> fix(ti-community-infra): make review approval act as lgtm

- prow/config/config.yaml
- prow/config/plugins.yaml
> feat(tikv/raft-engine): enable reviewing controlling

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> chore(pingcap/tiup): no need `ti-community-tar` plugin

- prow/config/external_plugins_config.yaml
also fix excludeLabels for tikv, pd
Fixes #1094
How it Works:
> REQUEST: deploy prow for pingcap/tidb-dashboard

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> feat(tikv/client-go): enable cherrypicker plugin

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
- prow/cronjobs/label-sync.yaml
What's Changed: enable some basic plugins and tide to control reviewing and merging.
How it Works:
> feat(tikv/client-rust): enable prow bot

- prow/config/plugins.yaml
> fix(pingcap/tidb-dashboard): forward event to cherrypicker external plugin

- prow/config/config.yaml
> feat(tikv/client-go,tikv/client-rust): add protection rules

- prow/config/config.yaml
update reuqired status in pd branch release-5.4
> config(tikv/pd): update reuqired status in pd branch release-5.4

- prow/cronjobs/branch-protector.yaml
> opt(prow/cronjobs): split branch protection job to three jobs to speedup the running

- prow/config/config.yaml
allow bot account or bot app
How it Works:
test with a user that owned write right:
before the setting:
after the setting:
> feat(prow/config): limit the merge operation accounts

- prow/config/config.yaml
Use new pipelines on branch release-8.1 of tikv & tiflash, update required status.
> config(tikv&tiflash): use new pipeline on 8.1 of tikv & tiflash

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> feat(ti-community/test-prow): add check rules for issue for han worlds

- prow/config/external_plugins_config.yaml
> feat(ti-community/test-prow): add check rules for issue for han worlds (#1109)

- prow/config/external_plugins_config.yaml
> feat(prow/config): add issue title checker

- prow/config/plugins.yaml
> chore(prow/config): enable `issues` event type for format-checker plugin

- prow/config/external_plugins_config.yaml
> chore(prow/configs): forbid label or unlabel cherry-pick type labels

- prow/config/labels.md
- prow/config/labels.md.tmpl
- prow/config/labels.yaml
> feat(prow/config): add color to some labels

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
- prow/cronjobs/label-sync.yaml
> feat(tikv/client-c): enable prow bot for reviewing and merging

- prow/config/config.yaml
Switch to use pipeline triggerd by prow, so need to update tikv & tiflash 7.5 required status.
> config(tikv/tikv, pingcap/tiflash): update required status for release-7.5 branches

- prow/config/config.yaml
Switch to use pipeline triggerd by prow, so need to update tikv & tiflash 7.1 required status.
> config(tikv & tiflash): update tikv & tiflash 7.1 required status

- prow/config/config.yaml
Switch to use pipeline triggerd by prow, so need to update tikv & tiflash 6.5 required status.
> config(tikv & tiflash): update required status for tikv&tiflash 6.5

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
> chore: support release 8.5

- prow/config/external_plugins_config.yaml
> fix(prow/config): execlude `type/cherry-pick-for-*` labels when create cherry-pick PR

- prow/config/labels.md
- prow/config/labels.yaml
> chore(prow/config): control affects type issue labels

- prow/config/external_plugins_config.yaml
- prow/config/plugins.yaml
> chore(pingcap/tidb-engine-ext): deploy ti-community-cherry-pick plugin for pingcap/tidb-engine-ext

- prow/config/config.yaml
only bot user can merge the PRs.
How it Works:
> fix(pingcap/tidb-engine-ext): strict the merge user

- prow/config/config.yaml
update required context on pd master branch.
Related PR https://github.com/tikv/pd/pull/8982.
> config(tikv/pd): pd update required context on master

- prow/config/config.yaml
Adjust required context of tide on pd master branch.
> config(tikv/pd): adjust required context of tide on pd master branch

- prow/config/config.yaml
add branch protection config for tidb-operator v2
> add branch protection for tidb-operator v2

- prow/config/config.yaml
> fix config in tidb operator v2

- prow/config/plugins.yaml
Update regex to match branch release-9.0-beta.M
> config(plugin-cherry_pick_unapproved): update regex to match release-9.0-beta.1

- prow/config/config.yaml
update required status checks of github action
> config(tikv/client-go): update required status checks of github action

- prow/config/config.yaml
add release-cloud to branch protection and tide settings.
> config(docs): add release-cloud to branch protection and tide settings

- prow/config/config.yaml
for repos:
- pingcap/monitoring
- pingcap/ng-monitoring
- pingcap/tidb-binlog
> chore(prow/configs): add license/cla to required status checks

- prow/config/config.yaml
- prow/config/external_plugins_config.yaml
Add trigger support for tikv/copr-test
> config(tikv/copr-test): add trigger support for tikv/copr-test

- prow/config/openai/tasks.yaml
Expanded the system message with detailed review steps and updated the user prompt to align with the new instructions.
> chore(prow/config/openai): update AI reviewer system message and user prompt

- prow/config/config.yaml
The issue was introduced by #1167
> fix(pigncap/tiflash): update release branch protection settings

- prow/config/plugins.yaml
- Move tekton and chatgpt plugins to org sections
- Enable forwording for new repo/org
> feat(prow/config): forword events for tekton

- prow/config/plugins.yaml
> chore(pingcap-inc/tici): set lgtm configuration

- prow/config/config.yaml
Reverts ti-community-infra/configs#1204
> Revert "config(tidb-operator): remove jenkins-ci / pull-e2e-kind-v2 from branch protection checks"
